- README.md
- config/config.go
- examples/aad-explicit-spn/main.go
- examples/custom-auth/main.go
> Improved examples

- CHANGELOG.md
- README.md
- version/version.go
* Improved usage instructions and added more documentation for services.
> Release v0.1.1

- client/client.go
This PR expands client to be compatible with Terraform provider
> Enable adding custom HTTP visitors

- client/client.go
> Fixed order of host completion

- .codegen/model.go.tmpl
- README.md
- openapi/code/named.go
- openapi/code/named_test.go
- service/billing/model.go
- service/clusters/model.go
- service/commands/model.go
- service/dbsql/model.go
- service/deployment/model.go
- service/instancepools/model.go
- service/ipaccesslists/model.go
- service/jobs/model.go
- service/libraries/model.go
- service/mlflow/model.go
- service/permissions/model.go
- service/pipelines/model.go
- service/scim/model.go
- service/secrets/model.go
- service/unitycatalog/model.go
- service/warehouses/model.go
- service/workspace/model.go
* Add runtime validation possibility for enums
* Loosely integrate with https://github.com/spf13/pflag by implementing [pflag.Value](https://pkg.go.dev/github.com/spf13/pflag#Value)
> Implement `pflag.Value` for enums

- .codegen/model.go.tmpl
- service/commands/model.go
- service/dbsql/model.go
- service/jobs/model.go
- service/pipelines/model.go
- service/tokenmanagement/model.go
- service/warehouses/model.go
* Explicitly annotated `any` type where needed
* Adjusted base OpenAPI spec
> Fixed missing field types

- internal/node_type_test.go
- service/clusters/node_type.go
Also remove `VCPU` selector that is deprecated and will be removed soon
> Add new node type selector

- .github/workflows/push.yml
- Makefile
Each major Go release is supported until there are two newer major releases.
> Test with Go 1.20

- config/config.go
Fix for https://github.com/databricks/terraform-provider-databricks/issues/2042
> Skip loading `~/.databrickscfg` when not required

- config/config.go
> add `isTesting` marker to support `ResourceFixture` in Terraform

- config/config_file.go
Debug messages would include a stringified version of the `configFile` object instead of the path.
> Update debug messages in config loader to display correct path

- openapi/code/package.go
Fixed external entity generation related to unity catalog package split
> Fix external entity generation

- service/compute/utilities.go
Invalid refactor in #389.
Ran TestAccLibraries manually to confirm this fixes the issue.
> Fix error handling in cluster utility function

- internal/workspace_test.go
Follow up to comment in #401.
Integration tests pass.
> Use constants instead of hardcoding strings

- .gitignore
- openapi/code/entity.go
Added IsAllRequiredFieldsPrimitive helper function
> Added IsAllRequiredFieldsPrimitive helper function

- .codegen/api.go.tmpl
Update API test template with page tokens added in https://github.com/databricks/universe/pull/320579
> [JOBS-12224] Update API test template with page tokens

- .codegen/accounts.go.tmpl
- account_client.go
> Don't panic but return error from NewAccountClient

- CHANGELOG.md
- version/version.go
> Release v0.10.1

- config/config.go
https://github.com/databricks/databricks-sdk-go/pull/530 merged before addressing one style issue from @shreyas-goenka.
> Address style issue in IsAccountClient()

- openapi/code/entity.go
Added HasRequiredNonBodyField method
> Added HasRequiredNonBodyField method

- service/iam/model.go
- service/jobs/model.go
- service/ml/model_registry_usage_test.go
Spec commit sha: 17a3f7fe6 (7 July 2023)
* Add EmailNotifications to jobs.SubmitRun and jobs.SubmitTask
* Add NotificationSettings to jobs.SubmitTask
> Regenerate Go SDK from current OpenAPI Specification

- CHANGELOG.md
- service/iam/model.go
- service/ml/model_registry_usage_test.go
- service/sql/model.go
- version/version.go
* Handled nested query parameters in Client.attempt ([#559](https://github.com/databricks/databricks-sdk-go/pull/559)).
* Supported x-databricks-path-style overrides at the operation level ([#562](https://github.com/databricks/databricks-sdk-go/pull/562)).
> Release v0.14.1

- .codegen/_openapi_sha
- service/iam/api.go
- service/iam/interface.go
- service/iam/model.go
- service/ml/model_registry_usage_test.go
- service/sql/model.go
- workspace_client.go
Updates to the OpenAPI spec as of 7 august 2023.
> Update OpenAPI spec 7 aug 2023

- service/compute/utilities.go
This PR adds a retry for timing edge cases like `INVALID_STATE: Cluster XXX is in unexpected state Pending.`
Other PRs:
- https://github.com/databricks/databricks-sdk-java/pull/134
- https://github.com/databricks/databricks-sdk-py/pull/283
> Retry in `w.Clusters.EnsureClusterIsRunning(id)` when cluster is simultaneously started by two different processes

- .github/workflows/push.yml
This silences a deprecation warning in the action run output.
n/a
> Update actions/checkout to v3

- .github/workflows/push.yml
This workflow doesn't need the full commit history, so we can skip it.
n/a
> Skip unshallow step in test workflow

- openapi/code/entity.go
Fixed HasRequiredNonBodyField method logic to be inline with the name and also checking for ` vsPath`, `IsQuery` values
- ~[ ] relevant integration tests applied~
> Fixed HasRequiredNonBodyField method

- openapi/code/entity.go
Added Field.IsRequestBodyField method for code generation
- ~[ ] relevant integration tests applied~
> Added Field.IsRequestBodyField method for code generation

- internal/catalog_test.go
Storage credentials and external locations were created but not removed.
Pass.
> More cleanup in Unity Catalog integration test

- openapi/code/package.go
- openapi/code/service.go
Fix stack overflow on recursive schemas
Tested by following these steps:
* Remove schema causing the issue from Universe
* Generate SDK using deco tool without the fix
* Generate SDK using deco tool with fix, and verify that there is no change
* Add back the schema causing the issue from Universe
* Generate SDK using deco tool with fix, and verify new structs manually
- [N/A] relevant integration tests applied
> Fix stack overflow on recursive schemas

- openapi/code/entity.go
> Add helper function

- openapi/code/entity.go
- service/catalog/model.go
- service/iam/model.go
- service/ml/model_registry_usage_test.go
- service/pipelines/model.go
Update isObject to consider empty objects
> Update isObject to consider empty objects

- config/api_client.go
- config/visitors.go
- config/visitors_test.go
- httpclient/api_client.go
- httpclient/api_client_test.go
> Support custom AuthVisitors

- CHANGELOG.md
- version/version.go
* Add a credentials provider for Github Azure OIDC ([#965](https://github.com/databricks/databricks-sdk-go/pull/965)).
* Add DataPlane API Support ([#936](https://github.com/databricks/databricks-sdk-go/pull/936)).
* Added more error messages for retriable errors (timeouts, etc.) ([#963](https://github.com/databricks/databricks-sdk-go/pull/963)).
* Add ChangelogConfig to Generator struct ([#967](https://github.com/databricks/databricks-sdk-go/pull/967)).
* Improve Changelog by grouping changes ([#962](https://github.com/databricks/databricks-sdk-go/pull/962)).
* Parse API Error messages with `int` error codes ([#960](https://github.com/databricks/databricks-sdk-go/pull/960)).
> Release v0.43.1

- .codegen/changelog_config.yml
- .github/workflows/push.yml
> [Internal] Enforce Tag on PRs

- apierr/error_overrides.go
Generate the errors on which we should retry
> Generate SDK for `apierr` changes

- CHANGELOG.md
- version/version.go
* Enforce Tag on PRs ([#969](https://github.com/databricks/databricks-sdk-go/pull/969)).
* Generate SDK for `apierr` changes ([#970](https://github.com/databricks/databricks-sdk-go/pull/970)).
* Add Release tag and Workflow Fix ([#972](https://github.com/databricks/databricks-sdk-go/pull/972)).
> [Release] v0.43.2

- .github/dependabot.yml
Add prefix to Dependabot commit messages
> [Internal] Add prefix to Dependabot commit messages

- .github/workflows/message.yml
Add comment to validate workflow
> [Internal] Add comment to validate workflow

- openapi/code/service.go
Add missing Package to Entity
```
make snapshot-localsdk
deco openapi release-sdk --no-reset-main --dry-run go --openapi-spec master
```
- N/A relevant integration tests applied
> [Fix] Add missing Package to Entity

- .github/workflows/check-mark.yml
- .github/workflows/integration-tests.yml
Add workflows manage integration tests checks. 
Appended the following code to the `integration-tests`.yml to simulate tests running
```
- name: Wait 10 seconds
run: sleep 10
- name: Trigger another workflow
env:
GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
run: |
gh workflow run check-mark.yml --repo databricks/databricks-sdk-go --ref enable-check \
-f pull_request_number=${{ github.event.pull_request.number }} \
-f check_run_id=${{ env.CHECK_RUN_ID }} \
-f test_run_id="potato" \
-f status="running"
- name: Wait 10 seconds
run: sleep 10
- name: Trigger another workflow
env:
GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
run: |
gh workflow run check-mark.yml --repo databricks/databricks-sdk-go --ref enable-check \
-f pull_request_number=${{ github.event.pull_request.number }} \
-f check_run_id=${{ …
```
> [Internal] Add workflows manage integration tests checks

- .github/workflows/check-mark.yml
- .github/workflows/integration-tests.yml
Improve integration test comment
> [Internal] Improve integration test comment

- .github/workflows/integration-tests.yml
Automatically trigger integration tests when a PR is opened or updated
Updated workflow triggered the tests. On success, the tests marked the check as succesfull.
> [Internal] Automatically trigger integration tests

- .github/PULL_REQUEST_TEMPLATE.md
This PR updates the PR template to remove outdated check boxes and emphasize testing.
N/A
> [Internal] Refresh PR template

- CHANGELOG.md
Update Changelog file. 
This file was not updated during the last release due it being manual and an oversight.
N/A
> [Fix] Update Changelog file

- .github/workflows/external-message.yml
- .github/workflows/integration-tests.yml
> [Internal] Migrate workflows that need write access to use hosted runners

- CHANGELOG.md
- service/apps/model.go
- service/billing/model.go
- service/catalog/model.go
- service/cleanrooms/model.go
- service/compute/model.go
- service/dashboards/model.go
- service/files/model.go
- service/iam/model.go
- service/jobs/model.go
- service/marketplace/model.go
- service/ml/model.go
- service/oauth2/model.go
- service/pipelines/model.go
- service/pkg.go
- service/provisioning/model.go
- service/serving/model.go
- service/settings/model.go
- service/sharing/model.go
- service/sql/model.go
- service/vectorsearch/model.go
- service/workspace/model.go
- version/version.go
* Do not send ForceSendFields as query parameters.
> [Release] Release v0.58.1
