openapi/code/package.go, openapi/code/tmpl_util_funcs.go, openapi/gen/main.go
This PR adds an advanced code generation feature for "main services" per package, which could be "flattened down" to the same namespace as the package itself, producing better end-user UX for the generated code. This manifests in the following templates:
package-level generation:
```
{{if .MainService -}}
// code for a package with a main service
{{load ".codegen/service.go.tmpl"}}
{{template "service" .MainService}}
{{- else -}}
// code for a package with multiple services
{{end}}
```
service-level generation:
```
{{if not .MatchesPackageName}}
{{template "service" .}}
{{else}}
{{skipThisFile}}
{{end}}
{{define "service"}}
// code for a service
{{end}}
```
=> Add concept of `main` service for the package

internal/dbfs_test.go, service/dbfs/doc.go, service/dbfs/utilities.go
I noticed ~30 API calls to download a 1.44M file from DBFS and it turns out that `io.ReadAll` starts out with a small buffer and grows it conservatively.
Through the `io.WriterTo` interface we can make the same reader use the maximum DBFS read size of 1MB and reduce the number of API calls for the same file down to 2.
This PR also contains a related fix for `FileReader.Read` such that it no longer requires a final zero-length read call.
=> Implement io.WriterTo for DBFS file reader

Makefile, openapi/code/entity.go, openapi/code/method.go, openapi/code/service.go, openapi/code/tmpl_util_funcs.go
* Renamed `~/bin/openapi-codegen` to `~/bin/oac`
* Added `HasQueryField` and `HasJsonField` for Entity
* De-duplicate entries in `Entity.RequiredOrder`
* Added `alphanumOnly` and `list` template helpers
=> Added more entity-generation utils

.codegen/api.go.tmpl, internal/clusters_test.go, retries/retries.go, service/clusters/api.go, service/commands/api.go, service/deployment/api.go, service/jobs/api.go, service/libraries/utilities.go, service/pipelines/api.go, service/sql/api.go
This PR ensures that `i.Info == nil` is a clear indicator for a long-running operation callback that it's run in the polling mode. For convenience, `retries.OnPoll` is added as well:
```go
clstr, err := w.Clusters.CreateAndWait(ctx, clusters.CreateCluster{
ClusterName:            clusterName,
SparkVersion:           latest,
InstancePoolId:         GetEnvOrSkipTest(t, "TEST_INSTANCE_POOL_ID"),
AutoterminationMinutes: 15,
NumWorkers:             1,
}, retries.Timeout[clusters.ClusterInfo](20*time.Minute),
retries.OnPoll(func(i *clusters.ClusterInfo) {
t.Logf("cluster is %s", i.State)
}))
```
Fixes #251
=> Cleaner callbacks for polling status

CHANGELOG.md, README.md, version/version.go
* Added `DATABRICKS_AUTH_TYPE` environment variable ([#248](https://github.com/databricks/databricks-sdk-go/pull/248)).
* Added Policy Families API ([#263](https://github.com/databricks/databricks-sdk-go/pull/263)).
* Added experimental `ErrCannotConfigureAuth` and `ErrNotAccountClient` ([#237](https://github.com/databricks/databricks-sdk-go/pull/237), [#238](https://github.com/databricks/databricks-sdk-go/pull/238)).
* Added DBFS file handle that supports both reading and writing ([#261](https://github.com/databricks/databricks-sdk-go/pull/261)).
* Added `io.WriterTo` for DBFS file reader ([#249](https://github.com/databricks/databricks-sdk-go/pull/249)).
* Added `pflag.Value` interfaces for enums ([#234](https://github.com/databricks/databricks-sdk-go/pull/234)).
* Added support for …
=> Release v0.2.0

README.md, config/auth_azure_msi.go, config/auth_default.go, config/azure.go
Added native [Azure Active Directory Managed Identity](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) integration. Use `ARM_USE_MSI` & `DATABRICKS_AZURE_RESOURCE_ID` environment variables (or their configuration counterparts) to trigger this auth type.
Special thanks to @alexott for the research of zero-dependency MSI in scope of https://github.com/databricks/databricks-cli/pull/412
=> Added Azure MSI auth

README.md, config/auth_default.go
It is possible that both `GoogleCredentials` and `GoogleServiceAccount` are set. Because `GoogleCredentials` is self-contained, it should have priority over `google-id`. This mirrors behavior of the TF provider.
=> Let `google-credentials` take precedence over `google-id`

apierr/errors.go, client/client.go
The response body was read in multiple places before this change. To make response body logging possible this needed to be consolidated to a single place; the `attempt` function.
If there is a valid response the log will be of the form:
```
< HTTP/2.0 404 Not Found (RESOURCE_DOES_NOT_EXIST: ...)
```
=> Log error responses

config/auth_u2m.go
Propagating an empty host was causing `cannot fetch credentials` error.
=> Fixed bricks CLI auth

CHANGELOG.md, version/version.go
* Added support for GCP deployment APIs in Public Preview.
* Added new node type selector ([#287](https://github.com/databricks/databricks-sdk-go/pull/287)).
* Added Azure MSI auth ([#279](https://github.com/databricks/databricks-sdk-go/pull/279)).
* Added validation of strings in user agent package ([#291](https://github.com/databricks/databricks-sdk-go/pull/291)).
* Added logging for error responses ([#289](https://github.com/databricks/databricks-sdk-go/pull/289)).
* Update implementation of smallest node selection to match terraform's ([#273](https://github.com/databricks/databricks-sdk-go/pull/273)).
* Added experimental OAuth support ([#276](https://github.com/databricks/databricks-sdk-go/pull/276), [#266](https://github.com/databricks/databricks-sdk-go/pull/266), …
=> Release v0.3.0

internal/clusters_test.go, internal/secrets_test.go
As is, the integration tests created email addresses such as `sdk-go-sdk-go-bflaglaacell@example.com`.
=> Drop duplicate prefix in randomized email

apierr/errors.go
=> Fix `apierr.APIError` pointer receivers

config/auth_permutations_test.go, config/config_file.go
Fix #304
This issue unblocks https://github.com/databricks/terraform-provider-databricks/pull/1848
=> Skip loading config if auth is already explicitly configured directly

CHANGELOG.md, version/version.go
* Change APIError to use pointer receiver ([#298](https://github.com/databricks/databricks-sdk-go/pull/298)).
* Drop duplicate prefix in randomized email ([#299](https://github.com/databricks/databricks-sdk-go/pull/299)).
* Expand semver pattern to be compliant with https://semver.org ([#302](https://github.com/databricks/databricks-sdk-go/pull/302)).
* Fix `apierr.APIError` pointer receivers ([#307](https://github.com/databricks/databricks-sdk-go/pull/307)).
* Skip loading config if auth is already explicitly configured directly ([#306](https://github.com/databricks/databricks-sdk-go/pull/306)).
* Sync fixes for smallest node selection from Terraform ([#301](https://github.com/databricks/databricks-sdk-go/pull/301)).
* Updated from OpenAPI spec …
=> Release v0.3.1

config/auth_permutations_test.go, config/testdata/.databrickscfg
see https://github.com/databricks/databricks-vscode/pull/498 as reference.
=> Port auth tests from the JS SDK

CHANGELOG.md, version/version.go
* Allow AAD SPN authentication on Databricks Account level ([#311](https://github.com/databricks/databricks-sdk-go/pull/311)).
* Port auth tests from the JS SDK ([#313](https://github.com/databricks/databricks-sdk-go/pull/313)).
* Skip loading `~/.databrickscfg` when not required ([#314](https://github.com/databricks/databricks-sdk-go/pull/314)).
* Bump golang.org/x/net from 0.6.0 to 0.7.0 ([#312](https://github.com/databricks/databricks-sdk-go/pull/312)).
=> Release v0.3.3

config/config_file.go
Checking for presence of `host` isn't enough as it should happen only on Azure, so checking with `IsAzure` works better.
=> Don't load `~/.databrickscfg` if `azure-cli` auth is implicitly configured

CHANGELOG.md, README.md, version/version.go
* Added `id` field to the `NodeTypeRequest` for easier integration with Terraform's [databricks_node_type](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/node_type) data source ([#325](https://github.com/databricks/databricks-sdk-go/pull/325)).
* Don't load `~/.databrickscfg` if `azure-cli` auth is implicitly configured ([#324](https://github.com/databricks/databricks-sdk-go/pull/324)).
* Fixed newline in codegen comments ([#326](https://github.com/databricks/databricks-sdk-go/pull/326)).
* Update from OpenAPI ([#320](https://github.com/databricks/databricks-sdk-go/pull/320), [#328](https://github.com/databricks/databricks-sdk-go/pull/328)).
API changes:
* Renamed `deployment.AwsCredentials` to `deployment.CreateCredentialAwsCredentials`.
* Renamed …
=> Release v0.4.0

config/auth_u2m.go, config/config.go
Especially for the VS Code extension this is easier and more robust than messing the the `PATH`
=> Add option to configure the location of the bricks CLI

CHANGELOG.md, account_client.go, service/gitcredentials/model.go, service/oauth2/api.go, service/oauth2/impl.go, service/oauth2/interface.go, service/oauth2/model.go, service/pkg.go, version/version.go
* Added Delta Live Tables events method to `pipelines.PipelinesAPI` ([#339](https://github.com/databricks/databricks-sdk-go/pull/339)).
* Added `id` field to the `SparkVersionRequest` for easier integration with Terraform's [databricks_spark_version](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/spark_version) data source ([#335](https://github.com/databricks/databricks-sdk-go/pull/335)).
* Improve auth fixture capturing ([#336](https://github.com/databricks/databricks-sdk-go/pull/336), [#337](https://github.com/databricks/databricks-sdk-go/pull/337)).
* Make logger context aware and added examples of usage together with [`zerolog`](https://github.com/databricks/databricks-sdk-go/tree/main/examples/zerolog) and …
=> Release v0.5.0

.github/PULL_REQUEST_TEMPLATE.md
An additional "\n" got in comments due to editing on editor vs terminal.
=> Remove extra space in comments of PR Template

openapi/code/method.go, openapi/code/service.go, openapi/code/wait.go
- Adds named `Wait` the level of services
- Allow generating independent wait methods on the level of services
- `Waits` are named as `wait_<poll-method>_<service-singular>_<success-states>`
=> Adds named `Wait` the level of services

config/config.go, config/config_file.go
Export type for a loaded configuration file such that downstream applications can read its contents in the same way the SDK does. Rename the loader instance to `ConfigFile` to make it symmetric with `ConfigAttributes`.
This doesn't change functionality.
=> Add type to represent a loaded configuration file

config/auth_azure_msi.go, config/config.go
Added support for providing client id for MSI use case with multiple MSIs attached to an azure vm.
Manually tested on a vm with multiple MSI.
Created failure first:
Same VM:
=> Pass `azure_client_id` to Azure MSI if specified

CHANGELOG.md, README.md, version/version.go
* Added type to represent a loaded configuration file ([#349](https://github.com/databricks/databricks-sdk-go/pull/349)).
* Added named `Wait` the level of services ([#348](https://github.com/databricks/databricks-sdk-go/pull/348)).
* Pass `azure_client_id` to Azure MSI if specified ([#354](https://github.com/databricks/databricks-sdk-go/pull/354)).
* Bump google.golang.org/api from 0.112.0 to 0.114.0 ([#344](https://github.com/databricks/databricks-sdk-go/pull/344)).
=> Release v0.6.0

CHANGELOG.md, README.md, config/auth_azure_msi.go, config/auth_default.go, config/auth_metadata_service.go, internal/scim_test.go, version/version.go
* Update from OpenAPI ([#359](https://github.com/databricks/databricks-sdk-go/pull/359)).
* Experimental credentials provider via local server ([#340](https://github.com/databricks/databricks-sdk-go/pull/340)).
* Added `isTesting` marker to support `ResourceFixture` in Terraform ([#358](https://github.com/databricks/databricks-sdk-go/pull/358)).
* Bump golang.org/x/mod from 0.9.0 to 0.10.0 ([#356](https://github.com/databricks/databricks-sdk-go/pull/356)).
* Bump google.golang.org/api from 0.114.0 to 0.115.0 ([#357](https://github.com/databricks/databricks-sdk-go/pull/357)).
=> Release v0.7.0

config/auth_permutations_test.go, config/config.go, config/config_file.go
If a user specified a host to connect to without authentication details (either directly or via the `DATABRICKS_HOST` environment variable), the config file loader would load the profile named `DEFAULT` from the config file and overwrite whatever was already configured. This means it was possible to configure the host of workspace A and end up connecting to workspace B (if configured as `DEFAULT` profile in the config file). This PR prevents this behavior.
Also see https://github.com/databricks/databricks-sdk-go/issues/304.
- Added unit tests.
- Confirmed behavior with manual test.
=> Skip loading default profile if host is already configured

internal/permissions_test.go, internal/scim_test.go, internal/secrets_test.go
These tests left groups around that had to be removed manually/separately.
Manually ran changed integration tests.
=> Cleanup ephemeral groups in integration tests

client/body_logger.go, client/body_logger_test.go
When debugging problems, like, private link (that doesn't return JSON, but HTML message), etc., it's crucial to get correct error in case when non-JSON payload is returned.  This PR adds the logging of non-JSON payload as well
=> Body logger for non-JSON payload as well

openapi/code/named.go, openapi/code/tmpl_util_funcs.go, openapi/code/wait.go
- added `dict "k" "v" "k2" "v2"` function to construct `map[string]string{"k": "v", "k2": "v2"}`
- added `getOrDefault $dict "default value"`
- added `fmt` as template alias for `fmt.Sprintf`
- added `concat "a" "b" "c"` to join strings to "abc"
- added `TrimPrefix` on `*Named` to `(.TrimPrefix "account").CamelName`
=> Added more code generation utilities

CHANGELOG.md, version/version.go
* Added more code generation utilities ([#369](https://github.com/databricks/databricks-sdk-go/pull/369)).
* Body logger for non-JSON payload as well ([#365](https://github.com/databricks/databricks-sdk-go/pull/365)).
* Cleanup ephemeral groups in integration tests ([#368](https://github.com/databricks/databricks-sdk-go/pull/368)).
* Fixed external entity generation ([#372](https://github.com/databricks/databricks-sdk-go/pull/372)).
* Skip loading default profile if host is already configured ([#363](https://github.com/databricks/databricks-sdk-go/pull/363)).
* Update debug messages in config loader to display correct path ([#362](https://github.com/databricks/databricks-sdk-go/pull/362)).
* Bump golang.org/x/oauth2 from 0.6.0 to 0.7.0 …
=> Release v0.8.0

config/config.go, internal/mlflow_test.go
* Fix `TestAccClustersApiIntegration` acceptance test for mlflow on azure.
=> Fix mlflow acceptance tests

internal/mlflow_test.go
- Fix Mlflow integration test by checking status of model version and waiting for it to not be pending -- issue was happening due to race condition while deleting and status being pending leading to 409 status code.
- Use query parameters for delete
- Remove delete workaround
Ran integration test on PR:
- azure-prod: https://github.com/databricks/eng-dev-ecosystem/actions/runs/4854588429
- aws-prod: https://github.com/databricks/eng-dev-ecosystem/actions/runs/4854587272
Verified query parameters are supported for MLflow DELETE
=> Fixed MLflow integration test and removed workaround for `DELETE` query parameter

internal/clusters_test.go
The nightly clusters integration tests are failing because of duplicate cluster names in our testing workspaces. This PR removes a call to `ClusterInfoClusterNameToClusterIdMap` to make us robust against that 
Manually by running the acceptance test
=> Make clusters acceptance tests robust to duplicate cluster names

apierr/errors.go
Remove commented code from the error retry pathway. This is no longer needed and isn't included in any other SDKs.
=> Remove dead code from apierr/errors.go

openapi/code/tmpl_util_funcs.go
Added `in` codegen function
Regenerated Bricks CLI
=> Added `in` codegen function

client/client.go, internal/catalog_test.go
This change was introduced in https://github.com/databricks/databricks-sdk-go/commit/0dc1944411cd611ef4a92bc6a10eac379500dc55#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09L324, but it causes metastore deletion to fail.
=> Serialize params to request body on delete

CHANGELOG.md, README.md, internal/catalog_test.go, openapi/code/method.go, service/catalog/api.go, service/catalog/catalogs_usage_test.go, service/catalog/impl.go, service/catalog/interface.go, service/catalog/model.go, service/catalog/workspace_bindings_usage_test.go, service/ml/model_registry_usage_test.go, version/version.go
* Added more usage examples for `go doc` and Go Packages ([#389](https://github.com/databricks/databricks-sdk-go/pull/389)).
* Make OAuth work with new CLI ([#394](https://github.com/databricks/databricks-sdk-go/pull/394)).
* Update from OpenAPI spec ([#390](https://github.com/databricks/databricks-sdk-go/pull/390)).
* Bump github.com/stretchr/testify from 1.8.2 to 1.8.3 ([#393](https://github.com/databricks/databricks-sdk-go/pull/393)).
* Bump google.golang.org/api from 0.122.0 to 0.123.0 ([#392](https://github.com/databricks/databricks-sdk-go/pull/392)).
=> Release v0.9.0

internal/warehouses_test.go
This was changed in #389 without testing.
The function `w.Warehouses.DeleteByIdAndWait` always fails because upon deletion there is nothing left to GET and it returns a 404 error. For the sake of test cleanup, we can issue the delete and move on without waiting.
Ran TestAccSqlWarehouses manually to confirm this fixes the issue.
=> Fix cleanup logic in SQL warehouse integration test

internal/workspace_test.go
Broken by #389.
The test performs recursive listing and asserts the result is non-empty without first ensuring there is a file to list. This would sometimes pass and sometimes fail because tests are executed in parallel.
Ran TestAccWorkspaceRecursiveListNoTranspile manually.
=> Fix nondeterminism in workspace filesystem integration test

openapi/code/package.go
Code generator stores the defined types (entities) in `pkg.types` field. This field is primarily used for keeping the list of all observed types while generating code.
But if we use the entity stored in this map and modify it in-place, for example, add that some field is required, it will change the entity stored.
If later one we use this "cached" version of entity, it will contain modified configuration which can lead to unexpected results, for example, `User` entity in `Users.create` operation will have `ID` field as required even though based on OpenAPI definition it is not.
Thus, it's better not to use cached entities.
=> Do not use cached entities in code generation

openapi/code/package.go
This reverts commit 0af0ffcfe4e6ea977347ab107d16e5b2de9e7e41, otherwise, we miss the path parameters in the requests and break all SDKs
=> Revert "Do not use cached entities in code generation (#403)"

openapi/code/package.go, openapi/code/service.go
Added type update when entity fields are updated.
it also removes the caching, so every time we define an entity a new one is returned.
Keeping the cache would make the logic too complex, in particular
Case 1.
When we get the entity from cache but changing its fields, like [here](https://github.com/databricks/databricks-sdk-go/blob/main/openapi/code/service.go#L161), we can check if this field does not exist and the entity is from cache and create a new entity as a copy but with different name. The issue with that is
1. What if the field is removed and not added? We won't be able to detect this
2. New very similarly looking structuring will be created, which can cause confusion
3. The logic becomes a bit too complex
Case 2.
Let's say we process request which has no / less / different …
=> Added type update when entity fields are updated

openapi/code/method.go
=> Added isCrudCreate method

internal/dbfs_test.go, service/files/utilities.go
=> Error when opening a DBFS directory for reading

.codegen/api.go.tmpl, internal/jobs_test.go, internal/warehouses_test.go, service/compute/api.go, service/compute/utilities.go, service/iam/model.go, service/jobs/api.go, service/jobs/jobs_usage_test.go, service/ml/model_registry_usage_test.go, service/pipelines/api.go, service/provisioning/api.go, service/serving/api.go, service/sql/api.go, service/sql/model.go, service/sql/warehouses_usage_test.go, service/workspace/workspace_usage_test.go
* Deprecated `*AndWait` methods, will be removed in further releases. This PR keeps backwards compatibility for these methods.
* Introduced dedicated wait-for-state polling methods. This PR breaks compatibility for these methods and increases coherence with other SDKs
* `*API` clients with long-running semantics now always return an instance, that allows to optionally start polling
=> Introduce waiters as top-level methods

CHANGELOG.md, README.md, internal/init_test.go, internal/workspace_test.go, version/version.go
* Added log level support to SimpleLogger. Default logger now prints only `INFO` level messages. To replicate more verbose behavior from the previous versions, set the `DEBUG` level in `SimpleLogger` explicitly ([#426](https://github.com/databricks/databricks-sdk-go/pull/426)).
* Added `Upload` and `Download` methods where applicable ([#423](https://github.com/databricks/databricks-sdk-go/pull/423)).
* Added auth tests for a databrickscfg file with an empty DEFAULT profile ([#496](https://github.com/databricks/databricks-sdk-go/pull/496)).
* Added more integration tests and examples ([#503](https://github.com/databricks/databricks-sdk-go/pull/503)).
* Added preview level functions for services and methods to OpenAPI code ([#497](https://github.com/databricks/databricks-sdk-go/pull/497)). …
=> Release v0.10.0

openapi/code/method.go, openapi/model.go
Added OnlyPayload property for method
=> Added OnlyPayload property for method

openapi/code/method.go
=> Renamed IsJsonOnly method

config/config.go
As per https://docs.databricks.com/dev-tools/databricks-connect.html it's possible to provide cluster ID in Databricks configuration
This PR adds this field in Config struct
=> Added ClusterID field for Config

config/config.go, config/config_test.go
Modify IsAccountClient to return `true` for new accounts endpoints that are set up for the Department of Defense.
Resolves https://github.com/databricks/terraform-provider-databricks/issues/2433 once TF provider is updated to a version including this commit.
=> Support accounts-dod as account endpoint

CHANGELOG.md, version/version.go
* Regenerated from OpenAPI spec ([#527](https://github.com/databricks/databricks-sdk-go/pull/527)). Includes bugfixes for System Tables.
* Support accounts-dod as account endpoint ([#530](https://github.com/databricks/databricks-sdk-go/pull/530)).
Breaking API Changes:
- Renamed compute.ClusterInfo to compute.ClusterDetails
- Renamed compue.BaseClusterInfo to compute.ClusterSpec
- Renamed jobs.RunSubmitTaskSettings to jobs.SubmitTask
- Renamed jobs.JobTaskSettings to jobs.Task
- Renamed jobs.CreateJobFormat to jobs.Format
- Renamed jobs.JobsWebhookNotifications to jobs.WebhookNotifications
- Renamed jobs.CronSchedulePauseStatus to jobs.PauseStatus
- Renamed jobs.FileArrivalTriggerSettings to jobs.FileArrivalTriggerConfiguration
- Renamed jobs.GitSourceGitProvider to jobs.GitProvider
- …
=> Release 0.11.0

CHANGELOG.md, README.md, version/version.go
* Change release type
* Regenerate SDK according to OpenAPI spec ([#534](https://github.com/databricks/databricks-sdk-go/pull/534)).
* Bump google.golang.org/api from 0.128.0 to 0.129.0 ([#533](https://github.com/databricks/databricks-sdk-go/pull/533)).
=> Release v0.12.0

config/auth_azure_msi.go
Currently it is not possible to use azure msi authentication for accounts. This PR adds that functionality
Existing integration tests passing for azure-prod and azure-prod-acct
Need to test manually for MSI accounts auth
=> Make Azure MSI auth account compatible

openapi/code/named.go, openapi/code/named_test.go, openapi/code/package.go, service/compute/model.go, service/compute/node_type.go, service/compute/node_type_test.go, service/iam/model.go, service/jobs/model.go, service/ml/model_registry_usage_test.go, service/provisioning/model.go, service/sql/model.go
Currently, enum values that use camelCase or PascalCase are not split into separate words during the parse phase of the OpenAPI spec. As a result, `PascalCase()` returns `Camelcase` or `Pascalcase`, respectively. To fix this, I've modified SplitASCII to support parsing more forms (snake-case and constant-case), to split words based on all non-alphanumeric symbols, and to estimate the "case" of a number by looking at the neighboring letters.
=> Parse Camel Case and Pascal Case Enum Values

openapi/roll/ast.go
When generating the names of the arguments to use in methods named XByYAndZ (e.g. DeleteByJobId), the field names are derived from the name of the method. The logic for this was incorrect. This doesn't affect Go, since Go examples don't use the `.Request()` method on `call` but instead read from the call name and args directly.
=> Fix names of keyword arguments in examples

.github/workflows/push.yml
Add merge queue for Go SDK to support merging PRs which haven't been manually updated to latest main.
=> Enable merge queue for Go SDK

openapi/code/method.go, openapi/code/method_test.go
Adds extra naming schemes for generating other SDKs. Here's the table for all 3 types of names:
1. The normal method name appears in the workspace and account clients.
2. flattened name for R SDK, representing a function in a big namespace just for Databricks.
3. [cmdlet](https://learn.microsoft.com/en-us/powershell/module/az.keyvault/?view=azps-10.2.0)-like name, that represents a command it a global namespace, that contains not only Databricks.
Example of exceptions to general rules:
| `service`.`method` | flattened name | [cmdlet](https://learn.microsoft.com/en-us/powershell/module/az.keyvault/?view=azps-10.2.0) name |
| --- | --- | --- |
| model_registry.create_comment | create_model_comment | Create-DatabricksModelComment |
| model_registry.create_model | create_model | …
=> Add ability to generate flat names

CHANGELOG.md, version/version.go
* Added ability to generate flat names ([#568](https://github.com/databricks/databricks-sdk-go/pull/568)).
API Changes:
* Changed `Create` method for [a.AccountStorageCredentials](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#AccountStorageCredentialsAPI) account-level service to return [catalog.AccountsStorageCredentialInfo](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#AccountsStorageCredentialInfo).
* Changed `Get` method for [a.AccountStorageCredentials](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#AccountStorageCredentialsAPI) account-level service to return [catalog.AccountsStorageCredentialInfo](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#AccountsStorageCredentialIn …
=> Release v0.16.0

openapi/code/load.go, openapi/code/load_test.go, openapi/code/package.go, openapi/gen/main.go, openapi/generator/config.go, openapi/render/render.go, openapi/roll/tool_test.go
Small cleanup: use logger everywhere instead of printing to stdout.
=> Log consistently rather than printing to stdout

.codegen/impl.go.tmpl, apierr/errors.go, client/client.go, client/client_test.go, internal/files_test.go, openapi/code/load_test.go, openapi/code/method.go, openapi/code/service.go, openapi/code/wait.go, service/catalog/impl.go, service/compute/commands_test.go, service/iam/model.go, service/ml/model_registry_usage_test.go, service/oauth2/impl.go, service/pipelines/impl.go, service/serving/impl.go, service/sql/impl.go
The latest refactor of the client code in the Go SDK caused several regressions:
1. API calls using content-type: application/json apparently don't support transfer-encoding: chunked. To address this, I rewrite the internals of client.go to explicitly not wrap the bytes.NewReader or strings.NewReader in io.NopCloser. net/http's Client checks whether the body is a byte or string reader explicitly in order to set content-length and not use the chunked encoding.
2. UC API deletes that previously required query parameters in the body are not correctly serialized. However, the underlying issue has been fixed upstream, so we can remove all of this custom serialization code now.
3. Previously, the application/json Content-Type was sent with every request. However, there are some requests that …
=> Fix nightly test failures for Go SDK

.codegen/workspaces.go.tmpl, internal/acceptance_test.go, workspace_client.go
Analogous to #238.
This enables the CLI to return an error if a user attempts to use configuration for an account client with a workspace client.
Also see https://github.com/databricks/cli/issues/721.
New and existing integration tests pass (tested at workspace and account level).
=> Added `ErrNotWorkspaceClient`

openapi/code/service.go, openapi/model.go
The spec can contain the `x-databricks-request-type-name` annotation for requests that do not have a request body but need a request type to parameterize their URL path and query. This is necessary to 1) keep the method names for permissions APIs at the service level in check, and 2) have unique request type names.
When using this change with a new spec, the diff is (for the `JobsService`):
* `GetJobPermissionLevels` -> `GetPermissionLevels`
* `GetJobPermissions` -> `GetPermissions`
* `SetJobPermissions` -> `SetPermissions`
* `UpdateJobPermissions` -> `UpdateJobPermissions`
The request type names for these methods remain the same (because of this commit).
Manually confirmed that with this change the request type name is used if specified
=> Use an operation's request type name if specified

.github/workflows/push.yml
* Update to actions/setup-go@v4; this uses caching by default
* Run the build workflow on push to main to properly use the build cache
* Include Go 1.21 in the test matrix
n/a
=> Work on GitHub Action

config/auth_azure_cli.go, config/auth_azure_cli_test.go
Handle Azure authentication when WorkspaceResourceID is provided
Get token for the correct subscription 
* Created Unit tests
* Manually listed workspace cluster in the following scenarios:
* User with wrong default tenant. No WorkspaceResourceID provided: Fail (expected). WARN log emitted.
* User with wrong default tenant. WorkspaceResourceID provided: Succeed
* User with no subscription. No WorkspaceResourceID provided: Succeed. WARN log  emitted.
* User with no subscription. WorkspaceResourceID provided: Succeed (fallback mode, expected).
https://github.com/databricks/eng-dev-ecosystem/actions/runs/6038851262/job/16386160429
=> Handle Azure authentication when WorkspaceResourceID is provided

client/client.go, client/client_test.go, service/compute/commands_test.go
https://github.com/databricks/databricks-sdk-go/pull/590 made several changes in the error messages returned from the client. It turns out that many users depend on these error messages exactly. I'll revert this change for now to unblock users who depended on these error messages exactly. Going forward, we recommend that users check if the returned error is an API Error, and then to use the ErrorCode to make decisions about how to handle errors in the APIs.
=> Revert error message changes from client.go

config/auth_azure_cli.go, config/auth_azure_cli_test.go, config/testdata/az
The call to `oauth2.ReuseTokenSource` in `oauth_visitors.go` doesn't include a token to start with so will always trigger a new call to acquire a token.
We fix this by wrapping the `oauth2.TokenSource` with `oauth2.ReuseTokenSource` from the caller, where we have a copy of a valid token.
Calling `oauth2.ReuseTokenSource` twice is a no-op: https://cs.opensource.google/go/x/oauth2/+/refs/tags/v0.11.0:oauth2.go;l=370
This commit also updates the logging to emit the info line only once we know we can return from `Configure` successfully.
=> Reuse tokens after first call to Azure CLI

internal/files_test.go
Error messages changed in #592 and got reverted in #604.
This fixes the nightlies.
=> Update error message assertions

CHANGELOG.md, version/version.go
* Handled Azure authentication when WorkspaceResourceID is provided ([#597](https://github.com/databricks/databricks-sdk-go/pull/597)).
* Reverted error message changes from client.go ([#604](https://github.com/databricks/databricks-sdk-go/pull/604)).
* Reused tokens after first call to Azure CLI ([#605](https://github.com/databricks/databricks-sdk-go/pull/605)).
* Updated error message assertions ([#607](https://github.com/databricks/databricks-sdk-go/pull/607)).
=> Release v0.19.1

client/client.go, client/client_test.go
This problem was introduced in #592. It contains an assumption that a `nil` body on the newly introduced `requestBody` struct cannot be `nil`, yet it can be for requests without a body (HEAD, GET, and DELETE). If a request of one of these types fails with a retriable error (e.g. a 429), the code tries to reset the body, which in turn fails because it is nil.
The symptom is a GET request failing with: `cannot reset nil reader`.
Because a nil request body is valid, this change updates the expectation accordingly.
=> Fix case where retry of a request without body fails

CHANGELOG.md, version/version.go
* Fixed case where retry of a request without body fails ([#614](https://github.com/databricks/databricks-sdk-go/pull/614)).
Integration tests passed
=> Release v0.19.2

config/auth_azure_cli.go, config/auth_azure_client_secret.go, config/auth_azure_msi.go, config/oauth_visitors.go, config/oauth_visitors_test.go
By default, the oauth2 library refreshes a token 10 seconds before it expires. Azure Databricks rejects tokens that expire in 30 seconds. This leaves a 20-second window where the SDK assumes the token is valid while the backend rejects it.
This change extends the token expiry window to 40 seconds to fix this.
* Unit test for the expiry helper.
* Manually confirmed refreshes happen 40 seconds before actual expiry.
=> Adjust token expiry window to 40 seconds on Azure

config/auth_azure_cli.go, config/auth_azure_client_secret.go, config/auth_azure_msi.go
These are identical but were named differently.
n/a
=> Rename variables in Azure code to match across auth types

apierr/errors.go, client/client_test.go
Databricks API can return error details in case of errors. In some cases, users need to access such details to be able to solve the issue. This is the case for the errors of type ErrorInfo used by the UC catalog.
This PR adds the necessary fields to the APIError to Unmarshal the ErrorDetails and to expose the details of type ErrorInfo to the users.
=> Add details to APIError

CHANGELOG.md, version/version.go
* Adjust token expiry window to 40 seconds on Azure ([#617](https://github.com/databricks/databricks-sdk-go/pull/617)).
* Rename variables in Azure code to match across auth types ([#618](https://github.com/databricks/databricks-sdk-go/pull/618)).
* Add details to APIError ([#613](https://github.com/databricks/databricks-sdk-go/pull/613)).
* Fixed code generation of primitive types ([#623](https://github.com/databricks/databricks-sdk-go/pull/623)).
* Updated SDK to changes in OpenAPI specification ([#625](https://github.com/databricks/databricks-sdk-go/pull/625)).
API Changes:
* Changed `List` method for [a.AccountMetastoreAssignments](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#AccountMetastoreAssignmentsAPI) account-level service to return …
=> Release v0.20.0

internal/jobs_test.go, service/iam/model.go, service/jobs/jobs_usage_test.go, service/ml/model_registry_usage_test.go, service/sql/model.go
JobId was recently made optional for the cancel API. This means `CancelAllRunsByJobId` will no longer exist once we bump the SDK.
This PR removes usage of this method from our integration tests and examples to unblock SDK generation.
Existing tests
=> Remove use of cancel by job id in integration test

openapi/generator/config.go, openapi/render/render.go, openapi/roll/tool_test.go
This PR adds support in the codegen utility for template libraries. These are templates that are reused across multiple stages of code generation. For example, in the Java SDK, we need to compute the type of a field/parameter/return value multiple times in different phases of the SDK. This PR allows us to define these templates a single time and reuse them across multiple files. 
Added to the Java SDK and regenerated the SDK.
=> Add support for template libraries

CHANGELOG.md, version/version.go
Breaking API Changes:
* Changed `List` method for [a.AccountMetastoreAssignments](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#AccountMetastoreAssignmentsAPI) account-level service to return [catalog.ListAccountMetastoreAssignmentsResponse](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#ListAccountMetastoreAssignmentsResponse).
API Changes:
* Added [catalog.ListAccountMetastoreAssignmentsResponse](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#ListAccountMetastoreAssignmentsResponse).
Internal SDK Changes:
* Add support for template libraries ([#635](https://github.com/databricks/databricks-sdk-go/pull/635)).
OpenAPI SHA: bcbf6e851e3d82fd910940910dd31c10c059746c, Date: 2023-10-02
=> Release v0.22.0

config/auth_m2m.go
Right now we throw the error string: `"databricks OAuth is not supported for this host"`  without information on response status.
NA
=> Added log statement if OIDC response is non 200

CHANGELOG.md, version/version.go
Note: this release includes custom JSON marshalling that captures whether or
not a value is set and should be included in the marshalled output, if its
value is equal to Go's zero value (i.e. `0` for an int field).
* Add ForceSendFields and a custom marshaller ([#615](https://github.com/databricks/databricks-sdk-go/pull/615)).
* Support text/plain response as streaming request body ([#638](https://github.com/databricks/databricks-sdk-go/pull/638)).
* Added log statement if OIDC response is non 200 ([#644](https://github.com/databricks/databricks-sdk-go/pull/644)).
API Changes:
* Changed `Download` method for [a.BillableUsage](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/billing#BillableUsageAPI) account-level service to start returning …
=> Release v0.23.0

openapi/code/package.go
Small bugfix for the OpenAPI generator logging. The generator calls the `Load` method once per tag. That method iterates through all endpoints, skipping over the endpoints that are not tagged with the provided tag. Logging was done before checking this though, producing many extraneous logs.
Ran the generator against the CLI, producing far less noisy output.
=> Only log pkg.Load after checking whether the operation is tagged

openapi/code/method.go
Added CanSetRequiredFieldsFromJson method for OpenAPI generator
- ~[ ] relevant integration tests applied~
=> Added CanSetRequiredFieldsFromJson method for OpenAPI generator

internal/scim_test.go
Add integration tests for `Users`: `Patch`, `Update`
Solves #435
=> Add integration tests for `Users`: `Patch`, `Update`

internal/connections_test.go
Add integration tests for `Connections`: `Create`, `Delete`, `Get`, `List`, `Update`
Solves #433
=> Add integration tests for `Connections`: `Create`, `Delete`, `Get`, `List`, `Update`

openapi/code/entity.go, openapi/code/method.go
In attempt to simplify code generation logic (https://github.com/databricks/cli/pull/905) added separate methods for required path and body parameters and added Must/CanUseJson methods.
- ~[ ] relevant integration tests applied~
=> Added separate methods for required path and body parameters and added Must/CanUseJson methods

openapi/code/entity.go
Because path parameters can't be set via JSON input they can't be ooptional and therefore should be first in required fields list for generated commands
- ~[] relevant integration tests applied~
=> Make sure path parameters are first in order in RequiredFields

internal/catalog_test.go, internal/permissions_test.go, internal/sharing_test.go, service/catalog/metastores_usage_test.go, service/iam/workspace_assignment_usage_test.go
Statement Execution API is not supported in GCP, so we must skip any integration tests in GCP that use this API.
=> Skip GCP Integration Tests using Statement Execution API

openapi/code/tmpl_util_funcs.go
Adds a new function to template generation: `contains` is simply `strings.Contains`.
=> Added `contains` method in OpenAPI Generator

internal/sharing_test.go
The recipient activation flow in the SDK doesn't work properly today because the API requires that this request is sent to the host specified in the activation URL of the token generated when creating the recipient. Currently, the SDK only supports using the host from the static configuration. This does work in AWS and GCP today but purely by coincidence, so for now we will stop running these tests in Azure.
=> Skip recipients tests in Azure

internal/files_test.go
The test needs to be named TestUcAcc* to run in UC environments.
=> Allow Files API tests to run in UC environments

examples/slog/slog.go
`slog` evolved single this example was written. This PR updates it.
=> Update `slog` example with the correct interface

openapi/errors.go
Current default hierarchy is counter-intuitive:
example:
```
tests/integration/test_installation.py::test_jobs_with_no_inventory_database - databricks.sdk.errors.mapping.BadRequest: RESOURCE_DOES_NOT_EXIST: Could not find principal with name ucx_bgRu
```
=> Update mapping for `RESOURCE_DOES_NOT_EXIST` to inherit from `NOT_FOUND` and not `BAD_REQUEST`

config/auth_databricks_cli.go
The CLI produced a new error message during `databricks auth token` between v0.207.1 and v0.209.1 when no .databrickscfg file exists. This manifests primarily in unit tests which call the `databricks` CLI, but could also affect users using the SDK and CLI between these versions.
=> Handle "no configuration file found at" error during databricks-cli authentication

httpclient/api_client.go
This PR addresses a flaw in streaming response detection, where `application/json` was compared as a full string match instead of a prefix.
JSON media types might have more information after `application/json`, like `application/json;odata.metadata=minimal;odata...=...`.  See https://www.rfc-editor.org/rfc/rfc9110#section-8.3.1
=> Fixed response debug dump for extended JSON media types

CHANGELOG.md, apierr/error_mapping.go, config/environments.go, error_alias.go, service/catalog/external_locations_usage_test.go, service/catalog/storage_credentials_usage_test.go, service/catalog/volumes_usage_test.go, service/iam/model.go, service/ml/model_registry_usage_test.go, version/version.go
Major changes:
* There has been a major overhaul of error handling. Users can now compare errors in API responses to the well-known error responses defined in the `apierr` package and reexported in the `databricks` package. Users can check whether a specific error was returned, for example `errors.Is(err, databricks.ErrResourceAlreadyExists)`, rather than converting the error to `*APIError` to check the status code and error code. This change is backwards-compatible; users do not need to modify existing error-handling code when upgrading the SDK. See [#682](https://github.com/databricks/databricks-sdk-go/pull/682) and [#703](https://github.com/databricks/databricks-sdk-go/pull/703) for the changes and https://github.com/databricks/databricks-sdk-go/blob/main/error_alias.go for the full …
=> Release v0.26.0

client/client.go
In Terraform data sources for users & service principals use the SCIM List API with filter condition on user name or SP application ID. But SCIM API have relatively low concurrency limits and this lead to its overload and returning 429 to the internal backend:
```
HTTP/2.0 500 Internal Server Error
{
"detail": "REQUEST_LIMIT_EXCEEDED: Workspace 1234 exceeded the concurrent limit of 4 requests.",
"schemas": [
"urn:ietf:params:scim:api:messages:2.0:Error"
],
"status": "500"
}
```
But on that backend the error is converted to error with status 500 that isn't retriable by default.  This PR adds a substring `REQUEST_LIMIT_EXCEEDED` into the list of transient errors so it could be retried.
=> Retry request on `REQUEST_LIMIT_EXCEEDED` error returned by the SCIM API

config/auth_azure_cli.go, config/auth_azure_client_secret.go, config/auth_azure_msi.go, config/auth_permutations_test.go, config/azure.go, config/config.go, config/environments.go, config/environments_test.go
In testing scenarios when using a mock HTTP server, environment resolution will always return the AWS Prod environment, as that is the fallback. In order to mock out other environments, this PR exposes the fields of DatabricksEnvironment and the available AzureEnvironments, allowing users to configure custom environments in tests. Under test, if specified, the first value of the DatabricksEnvironments field is returned from the `Environment()` method.
=> Support overriding DatabricksEnvironment

httpclient/response.go
Without doing so, debug logs for HTTP fixtures are not showing bodies.
when calling APIs (AAD, ARM, ACR, ...) via `httpclient.ApiClient`, it's quite redundant to set the `Accept` header every time. This PR removes the need for such redundancy.
=> Detect `Accept` header in `httpclient.WithResponseUnmarshal`

httpclient/api_client.go, httpclient/request.go
This PR adds implicit `Content-Type` header detection to reduce boilerplate for middle-layer HTTP client code, because we already have 100% certainty about sending `application/json`, when we call `json.Marshal`.
=> Detect `Content-Type` header in `newRequestBody` for `httpclient`

apierr/errors.go, client/client.go, httpclient/api_client.go, httpclient/api_client_test.go, httpclient/errors.go
https://github.com/databricks/databricks-sdk-go/commit/b0f3c83d9f5eca12dbd4c1daa03e06aff98a94ff introduced a regression in the handling of errors returned from HttpClient.Do. Previously, only some errors returned by Client.Do() were retried; now, all are retried. This PR adds default error handling logic in httpclient for errors returned by Client.Do() matching the previous behavior. As part of this, we remove the duplicated transient error messages between apierr and the default client.
=> Wrap url.Error in APIError

config/auth_azure_client_secret.go, config/config.go, httpclient/api_client.go, httpclient/body_logger.go, httpclient/response.go, internal/acceptance_test.go
This PR uses per-config refresh context for all oauth2 tokens, so that it's separate from the context coming in the first request (as before)
=> Use per-config refresh context for OAuth tokens

CHANGELOG.md, version/version.go
This is a bugfix release, including a fix correcting issues with OAuth flows, due to a bug with the propagation of the response status in `httpclient`'s `RoundTrip()` implementation. This fixes the `failed during request visitor: token: oauth2: cannot fetch token: Response: {...}` error.
All fixes:
* Migrate Azure MSI & Metadata Service token sources to `httpclient` and add 100% test coverage ([#709](https://github.com/databricks/databricks-sdk-go/pull/709)).
* Added `config.NewAzureCliTokenSource` and `config.NewAzureMsiTokenSource` constructors ([#727](https://github.com/databricks/databricks-sdk-go/pull/727)).
* Use per-config refresh context for OAuth tokens ([#728](https://github.com/databricks/databricks-sdk-go/pull/728)).
=> Release v0.26.2

config/auth_m2m.go, config/auth_m2m_test.go, httpclient/fixtures/fixture.go, httpclient/fixtures/stub.go
This PR adds coverage of client-secret oauth for databricks on aws
=> Added 100% unit test coverage for `oauth-m2m`

openapi/code/entity.go, openapi/code/load.go, openapi/code/named_sort.go, openapi/code/package.go, openapi/code/service.go, openapi/code/wait.go
`github.com/databricks/databricks-sdk-go/httpclient/fixtures` stub generator uses Named.PascalName() method to come up with the best possible field name for generated copy-pastable stubs, though, when this library is attempted to be used together with github.com/spf13/viper, we immediately get the following error related to a change in golang.org/x/exp v0.0.0-20220722155223-a9213eeb770e as:
```
.../entity.go:185:32: type func(a *Field, b *Field) bool of func(a, b *Field) bool {…} does not match inferred type
...                        func(a *Field, b *Field) int for func(a E, b E) int,
```
because github.com/spf13/viper v0.17+ transitively depends on golang.org/x/exp v0.0.0-20230905200255-921286631fa9
This PR keeps the sorting behavior but removes dependency on code that changed in the …
=> Consolidate usage of named sorting

apierr/errors.go, client/client_test.go, common/request.go, common/response.go, config/config.go, httpclient/api_client.go, httpclient/api_client_test.go, httpclient/errors.go, httpclient/request.go, httpclient/response.go, logger/httplog/body_logger.go, logger/httplog/body_logger_test.go, logger/httplog/round_trip_stringer.go, logger/httplog/round_trip_stringer_test.go
Issues like https://github.com/databricks/terraform-provider-databricks/issues/3031 are difficult for users to debug when Databricks APIs respond with unexpected response bodies. This is often a bug in either the API (returning a non-JSON error message, for example) or from the caller (e.g. calling update but not specifying the ID of the resource to update), though it could also be due to a bug in the SDK itself. 
This PR improves the debuggability of errors returned from the SDK due to malformed responses or other failures to process the response by including the request log in the error, along with helpful text that points the user to report the issue at the Go SDK so it can be triaged and fixed.
The returned error's `Error()` method will produce a string like this:
unexpected error …
=> Improve debuggability of unexpected errors

openapi/code/service.go, openapi/generator/config.go
Support schema descriptions when generating SDK
Manually created specs have this form
```
{
"in": "path",
"name": "ip_access_list_id",
"required": true,
"description": "description here". <-------
}
```
Generated specs have this form
```
{
"in": "path",
"name": "ip_access_list_id",
"required": true,
"schema": {
"description": "description here"  <-------
"type": "string"
}
}
```
deco openapi generate-sdk cli --openapi-spec universe:~/universe
=> Support schema descriptions when generating SDK

common/response.go, common/response_test.go
Computing DebugBytes requires consuming the response body. In the client's main pathway, we don't use the response from the `*http.Request` field, but the OAuth implementation calling `RoundTrip()` does. This PR ensures that we reset the response for debug logging purposes.
=> Ensure that NewResponseWrapper resets the Body of the *http.Response if it is consumed for DebugBytes

CHANGELOG.md, version/version.go
This is a bugfix release that improves debuggability of unexpected errors ([#744](https://github.com/databricks/databricks-sdk-go/pull/744), [#750](https://github.com/databricks/databricks-sdk-go/pull/750)). When the SDK cannot deserialize a response from the Databricks REST API, the resulting error will include debugging information and instructions on how to submit a bug report to the SDK.
=> Release v0.28.1

apierr/errors.go, apierr/errors_test.go
Credential deletion fails with 409 and no response body if the credential is in use with a running workspace. This leads to some race conditions because workspace deletion is asynchronous, so attempting to delete a credential while a workspace is running will ultimately fail. This PR tolerates empty error bodies. Note that `Unwrap()` for APIError will delegate this to the appropriate status code-based error, so users can still use `errors.Is` to examine errors with no body.
=> Handle empty response for errors

internal/deployment_test.go, openapi/roll/tool.go, retries/retries.go, retries/retries_test.go
The SDK may return errors that users want to retry. For instance, a user that makes many SCIM operations in parallel and some fail with a Conflict may want to retry those failed requests. To simplify this process for users, this PR introduces a Retrier abstraction that allows users to configure the timeout for retries, a set of errors that should be retried, and/or a custom callback that can check whether a particular error should be retried. Example from this PR:
```go
t.Cleanup(func() {
err := retries.New[struct{}](retries.OnErrors(apierr.ErrResourceConflict)).Wait(ctx, func(ctx context.Context) error {
return a.Credentials.DeleteByCredentialsId(ctx, role.CredentialsId)
})
require.NoError(t, err)
})
```
I have used this to retry credential deletion in TestMwsAccWorkspaces.
=> Add utility to retry on specific errors

internal/deployment_test.go
Small fix for the integration test for TestMwsAccWorkspaces: 
1. we need to register the credential cleanup before the workspace cleanup so that we delete the credential after the workspace is deleted.
2. we are deleting the same credential twice due to a typo. Need to delete both credentials.
=> Fix integration test for TestMwsAccWorkspaces

CHANGELOG.md, openapi/roll/tool.go, service/iam/model.go, service/ml/model_registry_usage_test.go, service/sql/model.go, version/version.go
Other changes:
* Added RequiredPositionalArguments method for codegen ([#773](https://github.com/databricks/databricks-sdk-go/pull/773)).
* Support locking in integration tests ([#776](https://github.com/databricks/databricks-sdk-go/pull/776)).
* Update OpenAPI spec and fix incompatible changes ([#778](https://github.com/databricks/databricks-sdk-go/pull/778)).
API Changes:
* Added `Exists` method for [w.Tables](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#TablesAPI) workspace-level service.
* Added [w.LakehouseMonitors](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#LakehouseMonitorsAPI) workspace-level service.
* Added [catalog.CreateMonitor](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#CreateMonitor) …
=> Release v0.30.0

.github/workflows/push.yml
v1 has been deprecated for a long time and produces warnings in action output.
=> Update codecov/codecov-action to v3

config/auth_databricks_cli.go
Enable Databricks CLI auth for all clouds
```
databricks auth login
databricks current-user me
```
=> Enable Databricks CLI auth for all clouds

CHANGELOG.md, service/sql/model.go, version/version.go
Major changes:
* Enable Databricks CLI auth for all clouds ([#783](https://github.com/databricks/databricks-sdk-go/pull/783)).
Other changes:
* Update codecov/codecov-action to v3 ([#785](https://github.com/databricks/databricks-sdk-go/pull/785)).
* MustUseJson must be true if request is a map ([#786](https://github.com/databricks/databricks-sdk-go/pull/786)).
=> Release v0.30.1

.github/workflows/push.yml
This silences the following warning as seen in action output:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-go@v4.
=> Update actions/setup-go to v5

internal/account_client_test.go
Need to investigate why this doesn't work in Azure/GCP.
=> Skip AccountClient_GetWorkspaceClient() test in Azure/GCP

.codegen/impl.go.tmpl, httpclient/request.go, httpclient/request_test.go, openapi/code/load_test.go, openapi/code/method.go, openapi/code/package.go, openapi/code/service.go, openapi/model.go, openapi/testdata/spec.json
=> Support HEAD operations

openapi/code/load.go, openapi/code/package.go, openapi/code/service.go, openapi/model.go
Fix `any` references when generating code with circular dependencies
Generated Go SDK
=> Fix `any` references when generating code with circular dependencies

CHANGELOG.md, version/version.go
* Support creating a new workspace client from an account client ([#792](https://github.com/databricks/databricks-sdk-go/pull/792)). Please see the example:
```
// GetWorkspaceClient returns a WorkspaceClient for the given workspace. The
// workspace can be fetched by calling w.Workspaces.Get() or w.Workspaces.List().
//
// The config used for the workspace is identical to that used for the account,
// except that the host is set to the workspace host, and the account ID is
// not set.
a, err := databricks.NewAccountClient()
if err != nil {
panic(err)
}
ctx := context.Background()
workspaces, err := a.Workspaces.List(ctx)
if err != nil {
panic(err)
}
w, err := a.GetWorkspaceClient(workspaces[0])
if err != nil {
panic(err)
}
me, err := w.CurrentUser.Me(ctx)
```
* Added support to select …
=> Release v0.31.0

internal/catalog_test.go, openapi/roll/tool.go
The example generator can handle some custom code in integration tests. If we need to use retrier in integration tests, there is a specific format that is expected:
```
retrier.New().Wait(ctx, func() {
return ...
})
```
or
```
retrier.New().Run(ctx, func() {
return ...
})
```
This PR changes the UC catalog acceptance test to use this structure, as well as adds validation that no bare retriers are created.
=> Do not generate erroneous "r" and "w" samples

.codegen/impl.go.tmpl, .codegen/model.go.tmpl, httpclient/response.go, internal/files_test.go, openapi/code/entity.go, openapi/code/load_test.go, openapi/code/package.go, openapi/code/service.go, openapi/model.go, openapi/testdata/spec.json
Support header fields  in responses.
* Generated Go SDK. A new field was added:
```
// The name of the served model that served the request. This is useful when
// there are multiple models behind the same endpoint with traffic split.
ServedModelName string `json:"-" url:"-" header:"served-model-name,omitempty"`
```
* Run integration tests in PR (only AWS due to issues running workflows in EMU)
* Run files_test.go test after generation to validate changes to Content type.
=> Generate fields for headers in responses

httpclient/response.go, internal/files_test.go, openapi/code/method.go
Add helper function to get header fields. Used during Python SDK generation
- N/A relevant integration tests applied
=> Add helper function to get header fields

httpclient/response.go, internal/files_test.go
Add Int64 to header type injection
=> Add Int64 to header type injection

internal/workspace_client_test.go
This test should not be transpiled into a Python example.
=> Do not transpile getWorkspaceClient

httpclient/api_client.go, httpclient/api_client_test.go, httpclient/timeout_context.go, httpclient/timeout_context_test.go
The net/http package supports only a fixed timeout.
This is problematic when streaming a large request or response body.
The approach proposed in this PR is to disable the net/http timeouts and use our own context for cancellation instead. This context is canceled only if there is no activity for the duration of 1 timeout period. As the request or response body is read, the deadline is reinitialized to equal 1 timeout period from the current timestamp. This means real timeouts will still time out in the same amount of time, but streaming requests will not time out as long as there is activity.
If a request times out, it used to return the following error:
> Get "/a?": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Now it returns the following error:
> Get …
=> Adaptive request timeouts

CHANGELOG.md, version/version.go
* Fixed GetWorkspaceClient for GCP ([#803](https://github.com/databricks/databricks-sdk-go/pull/803)).
* Adaptive request timeouts ([#837](https://github.com/databricks/databricks-sdk-go/pull/837)).
* Added HTTP proxy example ([#825](https://github.com/databricks/databricks-sdk-go/pull/825)).
* Note: Backwards incompatible changes - Settings are now nested, please see the API changes below.
* Added:
- [w.PermissionMigration](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/iam#PermissionMigrationAPI) workspace-level service.
- [iam.PermissionMigrationRequest](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/iam#PermissionMigrationRequest).
- [iam.PermissionMigrationResponse](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/iam#Permissio …
=> Release v0.34.0

config/auth_permutations_test.go, config/config.go, config/config_attribute.go, config/config_attributes.go, config/config_auth_details.go, config/config_auth_details_test.go, config/config_file.go
Added Config.GetAuthDetails and use it in config debug string
Needed for https://github.com/databricks/cli/pull/1244
=> Added Config.GetAuthDetails

useragent/user_agent.go, useragent/user_agent_test.go
This PR ports https://github.com/databricks/databricks-sdk-py/pull/163 to the Go SDK. This enables partners who use the SDK through a tool (like Terraform) to add custom information to the user agent without having to make code changes to the tool.
Closes #850.
Added unit test to verify that the user agent is only updated when both DATABRICKS_SDK_UPSTREAM and DATABRICKS_SDK_UPSTREAM_VERSION are set.
Manually ran `examples/slog` to verify that the user agent is correctly updated.
=> Support DATABRICKS_SDK_UPSTREAM and DATABRICKS_SDK_UPSTREAM_VERSION

internal/sharing_test.go
A change was made recently to enable deletion vectors by default in new tables. However, this is incompatible with sharing, as shares don't currently support tables with deletion vectors, resulting in this failure:
```
Table property
delta.enableDeletionVectors
is found in table version: 0.
Here are a couple options to proceed:
1. Contact support to enable sharing of tables with Deletion Vectors or Column Mappings. Then share the table with history in UI or with SQL command: ALTER SHARE <share> ADD TABLE <table> WITH HISTORY. Note: Your recipients can only query these shared tables if they are using Databricks with DBR version 14.1 or higher, or using delta-sharing-spark with version 3.1 or higher.
2. Disable Deletion Vectors for the table with (`ALTER TABLE <table_name> SET TBLPROPERTIES …
```
=> Fix TestUcAccShares

internal/files_test.go
These tests are currently being skipped in integration tests. They run in the non-UC runner because the test name starts with TestAcc, but they are skipped there because metastore ID is not defined:
```
2024/03/26 02:08:32 [INFO] 🦥 TestAccUCUploadAndDownloadFilesAPI: === RUN   TestAccUCUploadAndDownloadFilesAPI
init_test.go:103: Environment variable TEST_METASTORE_ID is missing
--- SKIP: TestAccUCUploadAndDownloadFilesAPI (0.00s)
2024/03/26 02:08:32 [INFO] 🦥 TestAccUCDeleteFile: === RUN   TestAccUCDeleteFile
init_test.go:103: Environment variable TEST_METASTORE_ID is missing
--- SKIP: TestAccUCDeleteFile (0.00s)
2024/03/26 02:08:32 [INFO] 🦥 TestAccUCGetMetadata: === RUN   TestAccUCGetMetadata
init_test.go:103: Environment variable TEST_METASTORE_ID is missing
--- SKIP: …
```
=> Fix integration test naming for UC Files

.codegen/impl.go.tmpl, httpclient/request.go, httpclient/request_test.go, internal/files_test.go, openapi/code/entity.go, openapi/code/service.go, service/files/impl.go, service/iam/model.go, service/sql/model.go
Currently, path parameters are directly interpolated into the request URL without escaping. This means that characters like `/`, `?` and `#` will not be percent-encoded and will affect the semantics of the URL, starting a new path segment, query parameters, or fragment, respectively. This means that it is impossible for users of the Files API to upload/download objects that contain `?` or `#` in their name. `/` is allowed in the path of the Files API, so it does not need to be escaped.
The Files API is currently marked with `x-databricks-multi-segment`, indicating that it should be permitted to have `/` characters but other characters need to be percent-encoded. This PR implements this.
This PR builds on #868, correcting the test names for UC files.
=> Properly escape multi-segment path parameters

logger/httplog/round_trip_stringer.go, logger/httplog/round_trip_stringer_test.go
Besides the `Authorization` token, there are other tokens included by the SDK in requests in Azure & GCP with headers `X-Databricks-Azure-SP-Management-Token` and `X-Databricks-GCP-SA-Access-Token`. These need to be redacted as well unless DebugAuthorizationHeaders is set.
=> Do not leak secondary authorization tokens in debug logs

httpclient/api_client.go, httpclient/api_client_test.go
Because the debug string for requests/responses can contain percent characters, simply logging the request/response causes Go to interpret this as a format string. Instead, we should use format string `"%s"` to ensure that the percents are printed as expected to the debug log.
=> Fix logging of request bodies containing percent characters.

config/config.go, config/config_attribute.go
Added clientId and clientSecret to oauth-m2m auth_types
Fixes these 2 properties being incorrectly marked as not used in oauth-m2m authnetication.
=> Added clientId and clientSecret to oauth-m2m auth_types

test-config.yaml
There are a couple of flaky integration tests. This PR adds those to a configuration here so that our integration test runner doesn't fail when these specific tests fail.
=> Ignore flaky integration tests

.codegen.json, .codegen/error_overrides.go.tmpl, apierr/error_overrides.go, apierr/errors.go, apierr/errors_test.go, openapi/code/errors.go, openapi/errors.go, service/iam/model.go
Due to the eventually consistent nature of worker environment creation as a part of workspace setup, certain API requests can fail when made right after workspace creation. We have some exception handling for these in the SDKs, but a new case has appeared: "worker env WorkerEnvId(workerenv-XXXXX) not found" (see https://github.com/databricks/terraform-provider-databricks/issues/3452).
This PR addresses this issue. Furthermore, it moves the transient error messages into autogeneration so that there is a single source of truth that applies to all SDKs.
One other small change: I removed running unit tests from the autogeneration flow. It removes a small amount of convenience (users need to run `make test` after regenerating the SDK), but it speeds up the devloop when iterating on code …
=> Add retries for "worker env WorkerEnvId(workerenv-XXXXX) not found"

CHANGELOG.md, version/version.go
* Ignored flaky integration tests ([#894](https://github.com/databricks/databricks-sdk-go/pull/894)).
* Added retries for "worker env WorkerEnvId(workerenv-XXXXX) not found" ([#890](https://github.com/databricks/databricks-sdk-go/pull/890)).
* Updated SDK to OpenAPI spec ([#899](https://github.com/databricks/databricks-sdk-go/pull/899)).
Note: This release contains breaking changes, please see the API changes below for more details.
API Changes:
* Added `IngestionDefinition` field for [pipelines.CreatePipeline](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/pipelines#CreatePipeline), [pipelines.EditPipeline](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/pipelines#EditPipeline) and [pipelines.PipelineSpec](https://pkg.go.dev/github.com/databricks/dat …
=> Release v0.39.0

service/compute/library_utilities.go
There are a few issues with the response types for libraries APIs today. Recently, a breaking change was made in the return type of the ClusterStatuses() API, changing from ClusterLibraryStatus to ClusterStatusResponse. To unblock the release, I've implemented ToLibraryList() on this new type.
As a follow-up, I will unify the ClusterLibraryStatuses and ClusterStatusResponse structs into a single type and clean up any duplication that is introduced by this PR.
Using `replace` in the Terraform provider's `go.mod`, I made sure that the TF provider's code still compiles after renaming `ClusterLibraryStatus` to `ClusterStatusResponse`.
=> Add ToLibraryList() for ClusterStatusResponse

client/client_test.go, config/config.go, httpclient/api_client.go, httpclient/api_client_test.go, httpclient/fixtures/fixture.go, httpclient/traceparent/traceparent.go, httpclient/traceparent/traceparent_test.go
Currently, it is difficult to correlate requests made by a client with a request made by a backend service, especially if the same request is made multiple times. The REST API supports the [Trace Context standard](https://www.w3.org/TR/trace-context/) which defines a standard way of propagating tracing information through HTTP headers.
This PR implements a traceparent generator to construct new traceparent headers in accordance with this standard. These traceparents are attached to the headers of each individual request. The resulting header is visible when debug logs are enabled and DATABRICKS_DEBUG_HEADERS is set.
Added a unit test to ensure that new traceparents are set for every request.
It's hard to test that a debug log actually contains this header without rewriting a lot of the …
=> Add traceparent header to enable distributed tracing.

apierr/errors.go, httpclient/api_client.go, httpclient/api_client_test.go, logger/httplog/round_trip_stringer.go, logger/httplog/round_trip_stringer_test.go, retries/retries.go
Currently, we do not log requests that failed to complete or that failed when the SDK started processing the response. This means that requests that timeout due to a client-side timeout or canceled context are not logged, meaning that there is no visibility in the log of these kinds of requests.
This PR changes the request processing and error handling to ensure that all requests are logged, even those that are cancelled or fail due to other errors. The general approach is to process as much of the response as possible until encountering an error, log what we've retrieved, and then do any post-processing.
Some changes are needed in the roundtrip stringer to handle the case of a nil response.
Unit tests verify that canceled requests or nil responses are logged.
=> Log cancelled and failed requests

CHANGELOG.md, version/version.go
* Fixed codecov for repository ([#909](https://github.com/databricks/databricks-sdk-go/pull/909)).
* Add traceparent header to enable distributed tracing. ([#914](https://github.com/databricks/databricks-sdk-go/pull/914)).
* Log cancelled and failed requests ([#919](https://github.com/databricks/databricks-sdk-go/pull/919)).
* Bump golang.org/x/net from 0.22.0 to 0.24.0 ([#884](https://github.com/databricks/databricks-sdk-go/pull/884)).
* Bump golang.org/x/net from 0.17.0 to 0.23.0 in /examples/zerolog ([#896](https://github.com/databricks/databricks-sdk-go/pull/896)).
* Bump golang.org/x/net from 0.21.0 to 0.23.0 in /examples/slog ([#897](https://github.com/databricks/databricks-sdk-go/pull/897)).
=> Release v0.40.1

CHANGELOG.md, service/iam/model.go, version/version.go
* Renamed `CredentialsProvider` to `CredentialsStrategy`.
* Create a method to generate OAuth tokens ([#886](https://github.com/databricks/databricks-sdk-go/pull/886)).
* Better error message when private link enabled workspaces reject requests ([#924](https://github.com/databricks/databricks-sdk-go/pull/924)).
* Update OpenAPI spec ([#926](https://github.com/databricks/databricks-sdk-go/pull/926)).
* Changed `List` method for [w.Connections](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#ConnectionsAPI) workspace-level service to require request of [catalog.ListConnectionsRequest](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#ListConnectionsRequest).
* Renamed [w.LakehouseMonitors](https://pkg.go.dev/github.com/databricks/databricks …
=> Release v0.41.0

test-config.yaml
This test is failing for the same reason as the other flaky SCIM tests.
=> Ignore additional flaky test

.codegen/accounts.go.tmpl, .codegen/api.go.tmpl, .codegen/impl.go.tmpl, .codegen/interface.go.tmpl, .codegen/mock_account_client.go.tmpl, .codegen/mock_workspace_client.go.tmpl, .codegen/service-pkg.go.tmpl, .codegen/workspaces.go.tmpl, openapi/code/package.go, openapi/code/service.go, openapi/model.go
Ignore DataPlane Services during generation until proper support is implemented
Generated SDK using local universe (which contains DataPlane services)
=> Ignore DataPlane Services during generation

CHANGELOG.md, version/version.go
* Ignore additional flaky test ([#930](https://github.com/databricks/databricks-sdk-go/pull/930)).
* Ignore DataPlane Services during generation ([#933](https://github.com/databricks/databricks-sdk-go/pull/933)).
* Update OpenAPI spec ([#934](https://github.com/databricks/databricks-sdk-go/pull/934)).
API Changes:
* Changed `List` method for [a.AccountStorageCredentials](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#AccountStorageCredentialsAPI) account-level service to return [catalog.ListAccountStorageCredentialsResponse](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/catalog#ListAccountStorageCredentialsResponse).
* Added [catalog.ListAccountStorageCredentialsResponse](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/cat …
=> Release v0.42.0

apierr/errors.go, apierr/errors_test.go
Parsing error messages from the `/api/2.0/preview/scim/v2/Me` API causes parsing errors because the API returns the HTTP status (i.e. an `int`) as error code instead of a `string`. For example:
```json
{
"error_code": 403,
"message": "Invalid access token."
}
```
This PR solves the problem by parsing the `error_code` field as a `string` no matter its type. 
Note that the implementation is overkill because it also converts _any_ literal to a string (e.g. `true` becomes `"true"`). We could guarantee that the behavior is limited to converting `int` to `string` by adding a custom [Unmarshaler](https://pkg.go.dev/encoding/json#Unmarshaler) but this didn't seem worth the additional code. 
This PR also:
- Refactors the code by removing the `APIErroBody` struct. The rationale is that the struct …
=> Parse API Error messages with `int` error codes

config/auth_azure_github_oidc.go, config/auth_azure_github_oidc_test.go, config/auth_default.go, config/config.go, go.mod, go.sum
_Note: this PR is a copy of PR #950 which could not be merged because of some unverified commits. Please check PR #950 for the original review and comments._
This PR adds a `CredentialsProvider` to authenticate with Azure from Github workflows. 
The code is inspired by a similar feature already implemented in the Python SDK. It works as follows:
1. Obtain an ID token from Azure leveraging the env variables `ACTIONS_ID_TOKEN_REQUEST_URL` and `ACTIONS_ID_TOKEN_REQUEST_TOKEN` as [explained here](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers).
2. Exchange that ID token for an auth token.
Added a test suite which covers all the added code paths. I've also confirmed in my own Github Action that the code is …
=> Add a credentials provider for Github Azure OIDC

openapi/generator/config.go
Add ChangelogConfig to Generator struct
=> Add ChangelogConfig to Generator struct

openapi/errors.go
These are necessary to handle a problem with timeouts in permissions fetching
=> Added more error messages for retriable errors (timeouts, etc.)

.github/workflows/message.yml
PRs in the merge queue are currently unable to be merged (and thus dequeued) because the `validate` workflow is not triggered. This PR fixes the problem by adding the missing triggering event.
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
=> [Internal] Trigger the `validate` workflow in the merge queue

httpclient/response.go, httpclient/response_test.go
Prior to this PR, `WithResponseUnmarshal` was unmarshalling a response body to a `bytes.Buffer` by:
1. Reading all the response body in a slice of bytes; and
2. Writing that slice in the receiving `bytes.Buffer`.
Step 1 unnecessarily increases the memory footprint as the response body is essentially stored twice in memory during unmarshalling. This PR fixes that problem by loading the body directly in the buffer without passing by an intermediate container. 
Added a few unit test to cover all unmarshalling types.
Memory benchmark:
```go
var longString = strings.Repeat("a", 1<<30) 
func BenchmarkWithResponseUnmarshal_byteBuffer(b *testing.B) {
b.ReportAllocs()
client := NewApiClient(ClientConfig{
Transport: hc(func(r *http.Request) (*http.Response, error) {
return &http.Response{ …
```
=> [Fix] Avoid loading the response bodies twice in memory when parsing `bytes.Buffer`

.github/dependabot.yml
This PR update the `dependabot.yml` file to only perform security update. 
Non-security update PRs can be disabled by setting `open-pull-requests-limit` to zero ([ref](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file)). This is a little counter-intuitive. The reason this works seems to be that Dependabot uses another internal limit for security updates.
=> [Internal] Configure Dependabot for security updates only

openapi/code/package.go, openapi/model.go
Inlined anonymous entities (object and enum) is discouraged. Rather, the proper way to define these entities is to declare them explicitly in the component part of the OpenAPI specification. 
This PR adds a warning to inform users that their schema contains the discouraged pattern.
This PR also includes a couple of noop refactoring to improve readability:
- Move the part responsible for handling references in its own function.
- Use a switch to emphasize that an entity can only be one of a fixed set of types.
=> [Internal] Log a warning when declaring inline entities 

.codegen/api.go.tmpl, service/billing/api.go, service/catalog/api.go, service/compute/api.go, service/compute/commands.go, service/compute/spark_version.go, service/compute/utilities.go, service/dashboards/api.go, service/files/api.go, service/iam/api.go, service/iam/model.go, service/jobs/api.go, service/marketplace/api.go, service/ml/api.go, service/oauth2/api.go, service/pipelines/api.go, service/provisioning/api.go, service/serving/api.go, service/settings/api.go, service/sharing/api.go, service/sql/api.go, service/sql/model.go, service/sql/utilities.go, service/vectorsearch/api.go, service/workspace/api.go, service/workspace/utilities.go
This PR changes the template to auto-generate Go code to enable mixins by leveraging Go embedding. 
One positive side-effect of this PR is that it significantly reduces the amount of auto-generated code.
After this change, methods can be overridden by adding the overriding method to the `ServiceNameAPI` struct. For example:
```go
// -------------------------------------------------------
// Generated code.
// -------------------------------------------------------
type FooService interface {
Foo() string
Bar() string
}
type FooAPI struct {
FooService
}
type fooImpl struct{}
func (impl *fooImpl) Foo() string {
return "foo"
}
func (impl *fooImpl) Bar() string {
return "bar"
}
// -------------------------------------------------------
// Method that shadows the original Foo method inherited …
```
=> [Internal] Enable mixins via struct embedding

openapi/errors.go
Added error override for Get Run similarly to Get Job. Error messages: https://github.com/databricks/universe/blob/2e44b4d42c0832acc3a06792cbb285609b77e956/elastic-spark-common/message/JobsMessages.scala#L555
=> [Internal] Add error mapping for GetRun

service/compute/ext_spark_version.go
- We need to filter out Graviton DBRs, otherwise `SelectSparkVersion` will fail with `spark versions query returned multiple results`
=> [Fix] Allowed filtering for graviton DBRs in `ClusterAPI.SelectSparkVersion`

openapi/code/load_test.go, openapi/code/service.go, openapi/testdata/spec_jobs_2.2.json
Pin certain endpoints in jobs API to use API 2.1 after the public documentation for Jobs migrates to the 2.2 API version.
Unit tests verify that only specific Jobs API paths are updated.
=> [Internal] Pin jobs APIs to 2.1 in SDKs

internal/account_client_test.go, internal/clusters_test.go, internal/warehouses_test.go
There are three issues affecting our integration tests today:
1. When authenticated as a service principal, GetWorkspaceClient only works if the target workspace is a UC-enabled workspace. Currently, the test targets a non-UC workspace, so I've changed it to target a UC workspace.
2. In our AWS environment, clusters/warehouses can only be created if they have an "Owner" tag. I've updated TestAccSqlWarehouses to add this tag corresponding to our team.
3. There was a change in the behavior of cluster listing. Previously, list clusters API would return recently terminated clusters. However, now that doesn't seem to be the case. I've raised this with the appropriate backend team. In the meantime, I've updated the integration test to do all listing operations while the cluster is running. …
=> [Internal] Fix integration tests

internal/account_client_test.go, internal/warehouses_test.go
This test should only be triggered in UC Account-level test runner.
=> [Internal] Fix GetWorkspaceClient test & GCP SQL Warehouse Creation test

examples/default-auth/main.go
This PR fixes the `default-auth` example which raised an out-of-bound exception if the account has less than 10 clusters.
Note: the goal of the example is to demonstrate the auth mechanism, not to iterate on workspaces. 
Unit test + run the example
=> [Fix] Fix default-auth example when less than 10 clusters

openapi/code/service.go
This new function on the service allows to get access to NameIdMap from service instead of list method as it was done previously. 
Previously in code generation relying on `.List.NameIdMap` could lead to undetermenistic behaviour if there were more than 1 List operation on service. Why this is allowed, service can have only 1 name to id method anyway.
Thus, new `Service.NamedIdMap` will find `NamedIdMap` from all methods it has and if there are more than 1 - will panic. 
Used here:
=> [Internal] Added Service.NamedIdMap

openapi/code/entity.go, openapi/code/load_test.go, openapi/code/package.go, openapi/model.go, openapi/testdata/spec_subservices.json
Add terraform aliases to Entity. Such that aliases can be used for names in terraform provider.
=> [Internal] Add terraform aliases to Entity

config/auth_azure_cli.go, config/auth_azure_cli_test.go, config/auth_azure_msi_test.go, config/testdata/az
Addresses https://github.com/databricks/terraform-provider-databricks/issues/3918.
The Azure CLI's `az account get-access-token` command does not allow specifying `--tenant` flag if it is authenticated via the CLI.
See https://github.com/hashicorp/go-azure-sdk/pull/910 for context; this implementation mimics the work done there.
Unit tests ensure that all expected cases are treated as managed identities.
Added an integration test to verify that this works on machines using MSI with the Azure CLI installed.
=> [Fix] Do not specify `--tenant` flag when fetching managed identity access token from the CLI

internal/billing_test.go
Update test to support new accounts.
New accounts don't have data from 2023.
=> [Fix] Update test to support new accounts

test-config.yaml
Temporary ignore Metastore test failures.
Test fails in new account due to limit on Metastores.
=> [Internal] Temporary ignore Metastore test failures

test-config.yaml
Add TestAccCreateOboTokenOnAws to flaky test list
=> [Internal] Add TestAccCreateOboTokenOnAws to flaky test list

apierr/errors.go, apierr/errors_test.go, client/client_test.go, httpclient/response.go
Some errors returned by the platform are not serialized using JSON (see https://github.com/databricks/databricks-sdk-go/issues/998 for an example). They are instead serialized in the form "<ERROR_CODE>: <MESSAGE>". Today, the SDK cannot parse these error messages well, resulting in a poor user experience.
This PR adds support for parsing these error messages from the platform to the SDK. This should reduce bug reports for the SDK with respect to unexpected response parsing. This PR also refactors the error deserialization logic somewhat to make it more extensible in the future for other potential error formats that are not currently handled.
This PR renames MakeUnexpectedError() to MakeUnexpectedResponse() in the `apierr` package. It also changes the return type to string. This makes the …
=> [Fix] Handle non-JSON errors

config/config.go, config/config_test.go
The SDK currently hangs when making API requests if the Host is set to a non-empty but invalid endpoint, such as `https://:443`. This PR adds a check during authentication to ensure that the hostname is defined, failing early if not. The underlying error is exported so other clients, such as the CLI or Terraform Provider, can provide specific advice when this happens.
Added a unit test for this case.
=> [Fix] Fail fast when authenticating if host is not configured

CHANGELOG.md, version/version.go
* Update SDK to latest OpenAPI spec ([#1057](https://github.com/databricks/databricks-sdk-go/pull/1057)).
Note: This release contains breaking changes, please see the API changes below for more details.
* Added `DefaultSourceCodePath` and `Resources` fields for [apps.App](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/apps#App).
* Added `Resources` field for [apps.CreateAppRequest](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/apps#CreateAppRequest).
* Added `Resources` field for [apps.UpdateAppRequest](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/apps#UpdateAppRequest).
* Added `Schema` field for [pipelines.CreatePipeline](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/pipelines#CreatePipeline).
* Added …
=> [Release] Release v0.48.0

httpclient/errors.go
This PR is a no-op that improves readability by using the status code constants from `http` instead of integer.
Unit tests.
=> [Internal] Use error names instead of codes in `errors.go`

service/jobs/ext_api.go, service/jobs/ext_api_test.go
Introduces extension for jobs GetRun call that paginates tasks and iterations arrays in the response. This change is necessary to prepare for jobs API 2.2 release that serves paginated response. Pagination is over once the `next_page_token` is absent from the response. The pagination logic is not exposed to the customer. 
Unit test and manual test. I wrote go code that called the new logic and verified that the returned result contained full object when the API was paginated.
=> [Internal] Update Jobs GetRun API to support paginated responses for jobs and ForEach tasks

CHANGELOG.md, version/version.go
* Update Changelog file ([#1091](https://github.com/databricks/databricks-sdk-go/pull/1091)).
* Update to latest OpenAPI spec ([#1098](https://github.com/databricks/databricks-sdk-go/pull/1098)).
Note: This release contains breaking changes, please see the API changes below for more details.
* Added [cleanrooms](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/cleanrooms) package.
* Added `DeletePublicWorkspaceSetting` method for [w.AibiDashboardEmbeddingAccessPolicy](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/settings#AibiDashboardEmbeddingAccessPolicyAPI) workspace-level service.
* Added `DeletePublicWorkspaceSetting` method for [w.AibiDashboardEmbeddingApprovedDomains](https://pkg.go.dev/github.com/databricks/databricks-sdk-go/service/settings#A …
=> [Release] Release v0.53.0

internal/dbsql_test.go
Update Queries tests. Due to backend changes, "/" character is not allowed anymore in the display_name field. 
Run the updated tests.
=> [Internal] Update Queries test

.github/workflows/push.yml, Makefile, httpclient/request_test.go, retries/retries.go, service/compute/ext_results.go, service/jobs/ext_api.go, service/sql/ext_utilities.go
This PR updates the version of staticcheck used to the latest version (0.5.1). This is needed for compatibility with recent versions of go. When running the current version (0.4.0) using go 1.23.4, I get the following error:
```
panic: Cannot range over: func(yield func(K, V) bool)
goroutine 323 [running]:
honnef.co/go/tools/go/ir.(*builder).rangeStmt(0x140084a1a30, 0x14008dcd900, 0x140088cdb00, 0x0, {0x100aa3ef0, 0x140088cdb00})
/Users/miles/go/pkg/mod/honnef.co/go/tools@v0.4.0/go/ir/builder.go:2181 +0x6dc
honnef.co/go/tools/go/ir.(*builder).stmt(0x140084a1a30, 0x14008dcd900, {0x100aa62d8?, 0x140088cdb00?})
/Users/miles/go/pkg/mod/honnef.co/go/tools@v0.4.0/go/ir/builder.go:2394 +0x1c0
honnef.co/go/tools/go/ir.(*builder).stmtList(...) …
```
=> [Internal] Bump staticcheck to 0.5.1 and add go 1.23 test coverage

.github/workflows/codeql.yml
With the recent security hardening, we can only use Databricks managed Github runners. This Repo currently uses the general `CodeQL` setup. Adding a custom codeql.yml to modify the runner group in the current setup.
This workflow is a test.
=> [Internal] Create custom codeql.yml

.github/workflows/codeql.yml, .github/workflows/external-message.yml, .github/workflows/push.yml
This PR updates the Github workflows to run on the `dev/sdk-mod` branch.
Tested by running these workflows on this PR. Integrations tests still need to be adjusted.
=> [Internal] Update workflows to run on the `dev/sdk-mod` branch

internal/workspace_test.go
What - The PR modifies the scope of directory traversal in the recursive list test. It limits the search to the ".sdk" directory, where the relevant notebook is created.
Why - The test was previously hitting API rate limits because it was scanning too many elements in the current traversing directory. By narrowing the scope to the ".sdk" directory, the test can now run more efficiently without encountering these limits.
This is itself an integration test.
=> [Internal] Scope the traversing directory in the Recursive list workspace test

Makefile
This PR introduces a download target which is a wrapper around `go mod download`. The rationale behind introducing this target is that we can change the underlying implementation of this target for `dev/sdk-mod` branch in which there is no go.mod at the root repository so we need to either manually run download for all the go modules or introduce a make target like [this](https://github.com/databricks/databricks-sdk-go/pull/1123/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52). One could say that we can just add this target for SDK mod but we need to update integration test workflows accordingly. I think this is a better way than having an if/else statement in the workflow.
Locally run `make download`
=> [Internal] Add download target to MakeFile

service/apps/impl.go, service/files/impl.go, service/oauth2/impl.go, service/pkg.go, service/sharing/impl.go
#1124 fixed the handling of APIs that use query parameters and a body simultaneously. After that change, query parameters are always sent, even if set to the zero value.
This PR addresses this, using the same logic for query parameters as for fields in the body: if a field is set to its zero value, it will be included in the query parameter if it is present in ForceSendFields.
This behavior is dependend upon in the Terraform provider. I'll be using it in https://github.com/databricks/terraform-provider-databricks/pull/4430 and verifying that there is no behavior change in the generated request.
When using this PR in Terraform, tests asserting that the path doesn't include query parameters pass.
=> [Fix] Do not send query parameters when set to zero value

CHANGELOG.md, version/version.go
* Do not send query parameters when set to zero value ([#1136](https://github.com/databricks/databricks-sdk-go/pull/1136)).
=> [Release] Release v0.56.1

config/auth_azure_cli_test.go, config/experimental/auth/auth.go, config/experimental/auth/auth_test.go
This PR enables async refreshes for cached token sources. 
This PR also: 
- Fixes a race condition bug in the unit tests by adding a small delay to the test refresh.
- Remove one test in AzureCLI that is not correct anymore due to how the code is structured. Refactoring this to guarantee that the test pass is not trivial and ultimately out of the scope of the new system — as the cached token source is the one providing the guarantee. 
Fix unit tests.
=> [Feature] Enable async refreshes for OAuth tokens

service/jobs/ext_api.go, service/jobs/ext_api_test.go
Introduces logic in extension for jobs GetJob call that paginates tasks and other arrays in the response. This change is necessary for SDK and API 2.2 compatibility. API 2.2 serves paginated responses as long as next_page_token field is present in the response. The pagination logic is not exposed to the customer.
I enabled API 2.2 calls by modifying URL string /api/2.2/jobs/get in service/jobs/impl.go. Then I ran unit test from service/jobs/ext_api_test.go
=> [Internal] Update Jobs GetJob API to support paginated responses

NEXT_CHANGELOG.md, service/jobs/ext_api.go, service/jobs/ext_api_test.go
Introduces logic in the extension for jobs ListJobs call. The extended logic accounts for the new response format of API 2.2. API 2.1 format returns all tasks and job_cluster for each job in the jobs list. API 2.2 format truncates tasks and job_cluster to 100 elements. The extended ListJobs logic calls GetJob for each job in the list to populate the full list of tasks and job_clusters.
I added logic that reads jobs from the list and produces custom iterator struct `expandedJobsIterator` that is supposed to mimic python generators. The goal is to only read necessary elements from the API endpoint and not more.
Unit tests and manual tests. Manual tests were done in two modes: using API 2.2 and using API 2.1. So this code is compatible with both API versions.
=> [Internal] Update Jobs `list` function to support paginated responses

NEXT_CHANGELOG.md, qa/poll/poll.go, qa/poll/poll_test.go
in #769, `poll.Simple` method was added to simplify mocking of waiter objects. However, this only allows testing of happy path where no error is returned.
This PR adds the equivalent `poll.SimpleError` method to returns an error instead.
=> [Internal] add `poll.SimpleError` to mock waiter objects returning errors

NEXT_CHANGELOG.md, service/jobs/ext_api.go, service/jobs/ext_api_test.go
Introduces logic in the extension for jobs ListRuns call. The extended logic accounts for the new response format of API 2.2. API 2.1 format returns all tasks and job_cluster for each run in the runs list. API 2.2 format truncates tasks and job_cluster to 100 elements. The extended ListRuns logic calls GetRun for each run in the list to populate the full list of tasks and job_clusters.
I added logic that reads runs from the list and produces custom iterator struct `expandedRunsIterator` that is supposed to mimic python generators. The goal is to only read necessary elements from the API endpoint and not more.
Unit tests and manual tests. Manual tests were done in two modes: using API 2.2 and using API 2.1. So this code is compatible with both API versions.
=> [Internal] Update Jobs `list_runs` function to support paginated responses

databricks/config/api_client.go, databricks/httpclient/api_client.go
`ApiClient` provides always all the information needed to replace `DatabricksClient` in the service client. The only thing missing is access to the Host and Account ID. This PR add these to the `ApiClient` config. In preparation to the migration.
No test, the new function will be tested indirectly as soon as the migration is completed.
=> [Internal] Prepare `ApiClient` to replace `DatabricksClient`.

NEXT_CHANGELOG.md, apierr/errors.go, apierr/errors_test.go, httpclient/response.go
This PR refactors the error parsing logic so that the SDK stop recommending reporting an issue in case of unexpected error. The rationale is that we do not have control over the error types that middleware might return. It is thus not possible to reliably identify if a parsing issue is due to a limitation of the SDK or to the error itself. 
This PR also slightly simplifies the code. 
Normal CI.
=> Stop recommending opening an issue in case of unknown error

compute/v2/ext_utilities.go, databricks/config/api_client.go, databricks/httpclient/api_client.go
This PR adds Clusters Mixins, which was previously deleted because we don't have waiters in the SDK. 
This PR also adds cloud information to the HttpClient Config as it is needed in the mixin.
Existing tests.
=> [Internal] Add Previously Removed Clusters Utilities

integration/clusters_test.go, integration/commands_test.go, integration/deployment_test.go, integration/instancepools_test.go, integration/jobs_test.go, integration/libraries_test.go
This PR re-enables tests that depend on waiters, which were previously disabled as we didn't have waiters.
This PR only tests.
=> [Internal] Re-Enable tests that depends on Waiters.

NEXT_CHANGELOG.md, internal/dbsql_test.go
As of April 7, 2025: Official support for the legacy version of dashboards has ended.
https://docs.databricks.com/gcp/en/sql/user/dashboards. Removing the test and keeping it commented out for context as discussed. 
N/A
=> [Internal] Remove `TestAccDashboards` as legacy dashboard creation on has been discontinued

NEXT_CHANGELOG.md, config/config.go, config/config_test.go
A recent refactor of U2M logic to the SDK introduced a small bug where a hostname with a trailing slash would be rejected when using `databricks auth login`, e.g. `databricks auth login --host https://myworkspace.cloud.databricks.com/`. This happens because `AccountOAuthArgument` and `WorkspaceOAuthArgument` both validate that the provided host does not have a trailing slash. Instead, we can tolerate hostnames ending with a slash by using the `CanonicalHostName()` method of `Config` to normalize the hostname, removing the unneeded trailing slash before passing the normalized hostname to U2M auth components. I have made a similar fix to `getOidcEndpoints`.
Unit tests are added to verify that `getOauthArgument` on `Config` works with normalized hostnames, and same for `getOidcEndpoints`.
=> Tolerate trailing slash

NEXT_CHANGELOG.md, config/auth_databricks_oidc.go, config/auth_databricks_oidc_test.go, config/auth_default.go, config/config.go, config/experimental/auth/oidc/oidc.go, config/experimental/auth/oidc/oidc_test.go, config/id_token_source_github_oidc.go, config/id_token_source_github_oidc_test.go, config/token_source_strategy.go
This PR adds a new way to authenticate by reading OIDC ID tokens from environment variables. By default, the new credential strategy attempts to read the token from `DATABRICKS_OIDC_TOKEN`. This default value can be overwritten by setting `DATABRICKS_OIDC_TOKEN_ENV`. 
The new authentication mode will be tested before Github OIDC. The rationale is that we consider setting up `DATABRICKS_OIDC_TOKEN` as a stronger signal of intent than enabling OIDC for the whole Github Action.
This PR also moves `IDTokenSource` in its own `oidc` package within the `experimental/auth` package to clarify that these interfaces are still being validated.
Complete test coverage of the new source.
=> Add support for OIDC ID token authentication using an environment variable.

NEXT_CHANGELOG.md, config/auth_azure_github_oidc.go, config/auth_default.go, config/experimental/auth/oidc/github.go, config/experimental/auth/oidc/github_test.go, config/experimental/auth/oidc/tokensource.go, config/experimental/auth/oidc/tokensource_test.go
This PR adds support to authenticate with [Account-wide token federation](https://docs.databricks.com/aws/en/dev-tools/auth/oauth-federation#account-wide-token-federation) from the following auth methods: `env-oidc`, `file-oidc`, and `github-oidc`.  
The PR also slightly re-organize the code by moving the OIDC token source and Github IDTokenSource in the `oidc` package.
Unit test + local validation.
=> Add support to authenticate with Account-wide token federation 

NEXT_CHANGELOG.md, config/auth_azure_msi_test.go, config/auth_default.go, config/auth_default_test.go, config/auth_m2m_test.go, config/auth_metadata_service.go, config/auth_metadata_service_test.go, config/auth_permutations_test.go, config/credentials/credentials.go, config/token_source_strategy.go, config/token_source_strategy_test.go
This PR refactors the default auth flow to surface authentication errors when an auth type is specified. 
One side effect of this change is that errors that were previously surfaced during the default auth flow are now swallowed and only accessible via trace log.  
The PR also slightly simplify the token source strategy.
Unit and integration tests.
=> Return auth error when auth type is set

config/auth_default.go
This PR adds changes `DefaultCredentials` to return `ErrCannotConfigureDefault` when it cannot determine the default auth type. The goal is to make it easier for clients (such as the Databricks CLI) to differentiate auth errors from config errors. 
N/A
=> Return `ErrCannotConfigureDefault` when `DefaulCredentials` cannot determine the default auth type.

Makefile
Pin make file dependency versions. We should not use latest since it can break without notice.
```
make build
make test
make doc
```
=> Pin make file dependency versions

NEXT_CHANGELOG.md, client/client.go, common/environment/environments.go, config/api_client.go, httpclient/api_client.go
The SDK has two clients which serve very similar purposes: `ApiClient` and `DatabricksClient`. This PR is a first step to pay to merge these two client into a single consistent client. Specifically, it brings some of the functionality from `DatabricksClient` in `ApiClient` in preparation for a change of code generation logic.
This PR also slightly changes the way the `ApiClient` default parameter values are set by moving the logic in its constructor. 
Unit and integration tests.
=> Start decoupling `ApiClient` and `DatabricksClient`.

NEXT_CHANGELOG.md, apierr/errors.go
`APIError.ResponseWrapper` is an experimental internal feature meant to enable some functionality in the Databricks CLI. As such, users should refrain from having dependency on that field. This PR helps make that contract clear. 
N/A
=> Explicitly mark `APIError.ResponseWrapper` as experimental.

NEXT_CHANGELOG.md, httpclient/api_client.go
Increase burst in rate limiter to the value of RateLimitPerSecond.
The current value of 1 means that even CLI commands that do 2 requests can have a sleep between them. This will increase speed of short-lived commands that do a few requests only.
The burst=1 also means that effective RPS is lower than target 15 RPS because if there is a mix of requests that are longer than 1/15s (default rate limit) and shorter than 1/15s the tokens are wasted.
The burst=1 comes from the initial commit https://github.com/databricks/databricks-sdk-go/commit/027c878a1709de251365a2417ebedc4185a53a94#diff-99ba62d54caf56e573f16c036acfae28d76ddaace9a914740a10f4e1d50b1bd8R420
which comes from this terraform provider commit https://github.com/databricks/terraform-provider-databricks/commit/6669a942e348c2f36d1a21b4 …
=> Increase burst for rate limiter
